### PR TITLE
Finally done with create project

### PR DESCRIPTION
**Pull request by RoyalSix**
need to beautify modal

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/107)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[src/js/components/core/ChangesReportSaver.js, line 7 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj4q-CGjwpFjA4GKWj:-KMj4q-CGjwpFjA4GKWk:-692795583) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ChangesReportSaver.js#L7)):_

> ``` JavaScript
>     //array of file path to dynammically create folder
>     var x = "report for " + checkName + " is " + report;
>     console.log(x);
> ```

Remove all console.log unless they are for errors

---

_[src/js/components/core/ProjectModal.js, line 107 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj58lFruQ-bkHyGiUQ:-KMj58lFruQ-bkHyGiUR:-1836078177) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L107)):_

> ``` JavaScript
>     }
>     else {
>       return <CreateProjectForm controlLabelTitle={"Name"} placeHolderText={"Enter name of project"}projectname={this.state.projectname}/>
> ```

Set strings to variables so they can be changed dynamically

---

_[src/js/components/core/ProjectModal.js, line 141 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj5DCy3CTFZh1pHRxX:-KMj5DCzS9N9AkQQ2Y1m:-1063890742) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L141)):_

> ``` JavaScript
>     },
>     handleKeyPress: function(e) {
>       if (e.charCode == 13) {
> ```

Why 13? Set a variable named `EnterKey` equal to 13 and compare against that instead

---

_[src/js/components/modules/lexical_check_module/lexical_checker/Door43DataFetcher.js, line 118 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj5PhRbjippJqtbbMx:-KMj5PhRbjippJqtbbMy:-1428671178) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/modules/lexical_check_module/lexical_checker/Door43DataFetcher.js#L118)):_

> ``` JavaScript
>                                               let totalChapterVerses = _chapter['verses'].length;
>                                               let numChapterVerses = 0;
>                                               for (let verse of _chapter['verses']) {
> ```

Replace tabs with spaces

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107)_

**Comment by EllDoubleYew** [comment]
Reviewed 11 of 13 files at r1.
Review status: all files reviewed at latest revision, 25 unresolved discussions.

---

_[src/js/components/core/ChangesReportSaver.js, line 7 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj2jL2uFAs21jIzCeO:-KMj2jL2uFAs21jIzCeP:612675153) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ChangesReportSaver.js#L7)):_

> ``` JavaScript
>     //array of file path to dynammically create folder
>     var x = "report for " + checkName + " is " + report;
>     console.log(x);
> ```

Remove these log statements for a pull to develop

---

_[src/js/components/core/ChangesReportSaver.js, line 14 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj2skMjY2lEW6zDXL6:-KMj2skMjY2lEW6zDXL7:-1770684841) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ChangesReportSaver.js#L14)):_

> ``` JavaScript
>       console.log(err) // => null
>       fs.readJson(filepath, function(err, data) {
>         console.log(data)
> ```

Remove log statements

---

_[src/js/components/core/CheckDataGrabber.js, line 1 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj3AdX0TQFZ1Ih25I_:-KMj3AdYA4r3fcmn72gX:-2115081078) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/CheckDataGrabber.js#L1)):_

> ``` JavaScript
> const React = require('react');
> ```

Why are you requiring react and these bootstrap elements? Is this a view somewhere that I am not seeing.

---

_[src/js/components/core/CreateNewProject.js, line 7 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj3Rafcj7mfdf9WYKS:-KMj3Rafcj7mfdf9WYKT:-558686289) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/CreateNewProject.js#L7)):_

> ``` JavaScript
> var project = {
>   createProject: function(manifest, projectName){
>     console.log(projectName);
> ```

Remove console logs

---

_[src/js/components/core/CreateNewProject.js, line 8 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj3cQFqZxJWIF1iA7h:-KMj3cQGT5HrD52KE2_D:-30497272) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/CreateNewProject.js#L8)):_

> ``` JavaScript
>   createProject: function(manifest, projectName){
>     console.log(projectName);
>     var currentProject = {
> ```

Comment that "these are things a project might need to have" somewhere. As far as I know some of these might be necessary and some not.

---

_[src/js/components/core/CreateNewProject.js, line 17 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj3lgFfLlWeGXBtDgw:-KMj3lgFfLlWeGXBtDgx:1231938706) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/CreateNewProject.js#L17)):_

> ``` JavaScript
>       }
>     };
>     for (var el in manifest) {
> ```

Lets just be verbose and call el element here. It took me a minute to figure out what el meant. 

---

_[src/js/components/core/CreateNewProject.js, line 22 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj3uKwf_JNxljOHC5A:-KMj3uKwf_JNxljOHC5B:677724793) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/CreateNewProject.js#L22)):_

> ``` JavaScript
>     try {
>       var file = fs.readdirSync(window.__base + 'src/js/components/modules');
>       for (var el of file) {
> ```

ibid

---

_[src/js/components/core/ProjectModal.js, line 18 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj4INlX13VxYzEeBkb:-KMj4INlX13VxYzEeBkc:541633902) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L18)):_

> ``` JavaScript
> const ProjectModal = React.createClass({
>   getInitialState: function() {
>     return {
> ```

Think about moving some of these states to the coreStore. Things like the project name could more than likely live there.

---

_[src/js/components/core/ProjectModal.js, line 69 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj4Z-zG0BgnXEHZTDv:-KMj4Z-zG0BgnXEHZTDw:636987139) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L69)):_

> ``` JavaScript
>   changeCreateProjectText: function() {
>     this.setState({
>       currentText: CoreStore.getCreateProjectText()
> ```

This is not how flux should be used. Rather than set the state from a store and have that update the view; just directly update the view in render() with the core store. The re-render will happen for you without state. Flux takes a lot of state away from modules and "gives them" to stores. See line 124 to get an idea of what I mean by that.

---

_[src/js/components/core/ProjectModal.js, line 98 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj5NRFiMxqJoldip-W:-KMj5NRFiMxqJoldip-X:1278975887) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L98)):_

> ``` JavaScript
>         for (var el of file) {
>           if (this.isModule((window.__base + 'src/js/components/modules/' + el), el)) {
>             currentChecks.push(el);
> ```

Lets go with verbose names here again, element instead of el

---

_[src/js/components/core/ProjectModal.js, line 118 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj5RlBs8XxxDN_Of5Z:-KMj5RlBs8XxxDN_Of5_:-646264125) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L118)):_

> ``` JavaScript
>   render: function() {
>     return (
>       <div>
> ```

Indentation needs to be fixed for this render!

---

_[src/js/components/core/ProjectModal.js, line 124 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj52UdcM7LCwm8h8Jl:-KMj52UdcM7LCwm8h8Jm:43041413) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L124)):_

> ``` JavaScript
>       </Modal.Header>
>       <Modal.Body>
>       {this.getCurrentText()}
> ```

Instead of this.getCurrentText(), lets stick with flux and use CoreStore.getCreateProjectText().

---

_[src/js/components/core/ProjectModal.js, line 137 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj5Z6QUwsSSWqkWkf9:-KMj5Z6QUwsSSWqkWkfA:231417089) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L137)):_

> ``` JavaScript
>     getInitialState: function() {
>       return {
>         projectname:this.props.projectname
> ```

This does not need to be a state. Anywhere you would call this just call this.props.projectname. We want to aim for as few states as possible. see line 142 to see what I mean.

EDIT: This is actually a more complex issue. I see you are changing projectname here in the component; I understand why you used state but this should still not warrant a state. Rather than creating a state, make a setProjectName(string) function in your parent and pass it as a callback to this component. I know that might sound dumb but duplicating states is just a major no-no in react, we shouldnt have a state in a child with the same name as a state in the parent that is changing values that the parent does not know about. Everything should be reported to the parent through a callback and the PARENTS STATE should be changed not the childs and then it will trickle down. Come talk to me if you need any help with this.

---

_[src/js/components/core/ProjectModal.js, line 141 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj5DCy3CTFZh1pHRxX:-KMj5f9JADScADCbH0eT:-873036791) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L141)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> Why 13? Set a variable named `EnterKey` equal to 13 and compare against that instead
> </details>
> Agreed, 13 makes me wonder what is going on, having a const will greatly improve readability. 

---

_[src/js/components/core/ProjectModal.js, line 142 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj5yxx9CMdxJXHgfuc:-KMj5yxx9CMdxJXHgfud:1939477317) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L142)):_

> ``` JavaScript
>     handleKeyPress: function(e) {
>       if (e.charCode == 13) {
>         project.createProject(manifest, this.state.projectname);
> ```

Rather than this.state.projectname use this.props.project name. Kill the states of this component. 

---

_[src/js/components/core/ProjectModal.js, line 145 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj6v3J62uFiDQ8uBCW:-KMj6v3J62uFiDQ8uBCX:2126543677) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L145)):_

> ``` JavaScript
>       }
>     },
>     handleChange: function(e) {
> ```

This should be in parent and passed down as a callback rather than having its own function in the child, see my comment on 137 to see what I am talking about.

---

_[src/js/components/core/ProjectModal.js, line 151 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj64LkQJA3g_ci873Z:-KMj64LkQJA3g_ci873_:-1243177038) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L151)):_

> ``` JavaScript
>     },
>     render: function() {
>       return (
> ```

Indentation on render please!

---

_[src/js/components/core/ProjectModal.js, line 163 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj7rmJkSZJI6OwZvrZ:-KMj7rmJkSZJI6OwZvr_:735513899) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L163)):_

> ``` JavaScript
>     const SelectCheckType = React.createClass({
>       getInitialState: function(){
>         return {
> ```

lets lose these states and pass callbacks to this component instead.

---

_[src/js/components/core/ProjectModal.js, line 168 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj7EPJniSdhBaln7iG:-KMj7EPJniSdhBaln7iH:670594982) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L168)):_

> ``` JavaScript
>         };
>       },
>       onClick_: function(e) {
> ```

This function has a number of problems. First lets name it appendFetchDataArray_ rather than onClick_ just so we have a better idea of what it does. Second we dont need to push anything to a state, this is a one way train to an error that is not traceable on the stack, this can cause serious problems down the line. What we should do is create a new local variable from the _prop_ not the _state_. Lose the states and create a copy of your props, append your local variables and send them back up to the parent states with a callback. Again this is very similar to the problem I was talking about above. States need to stay in the parent, talk to me if you need help with this.

---

_[src/js/components/core/ProjectModal.js, line 187 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj7xS56Ym5AyZafSaS:-KMj7xS56Ym5AyZafSaT:-1836147946) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L187)):_

> ``` JavaScript
>       render: function() {
>         var checkButtonComponents = this.props.checks.map(function(checks) {
>           return (
> ```

Indentation on render functions

---

_[src/js/components/core/ProjectModal.js, line 189 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj80YOWaD2H_xdf34P:-KMj80YOWaD2H_xdf34Q:-815475676) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/components/core/ProjectModal.js#L189)):_

> ``` JavaScript
>           return (
>             <div>
>             <Checkbox id={checks} ref={checks}>
> ```

Is there a reason we are using ref here? Ref is generally reserved so that parents can call specific child components, is that what you are trying to do?

---

_[src/js/stores/CoreStore.js, line 157 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMj8LgaBth6gMQvFsog:-KMj8LgaBth6gMQvFsoh:-110854771) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7cf101678bb855de90c9ece367e4811b47e4dc85/src/js/stores/CoreStore.js#L157)):_

> ``` JavaScript
>       case consts.CHANGE_BUTTTON_STATUS:
>       this.buttonStatus = action.buttonStatus;
>       this.emitChange();
> ```

Lets fix some of the indentation here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107)_

**Comment by ihoegen** [comment]
Reviewed 9 of 12 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 26 unresolved discussions.

---

_[check_data.json, line 0 [r3]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMyzh4fkwiUYwMujHaM:-KMyzh4g9lw-Lq66K7H9:1723207724) ([raw file](https://github.com/wycliffeassociates/8woc/blob/116957d2acc6c460caa60dd8814108a28f943d04/check_data.json#L0)):_
This should be deleted

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107)_

**Comment by EllDoubleYew** [comment]
Reviewed 1 of 13 files at r1, 11 of 12 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 27 unresolved discussions.

---

_[src/js/components/core/CheckDataGrabber.js, line 37 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KMyVSGGkXr6WQYMAIbi:-KMyVSGGkXr6WQYMAIbj:1677251048) ([raw file](https://github.com/wycliffeassociates/8woc/blob/b0db9b4194ad416bb83237ac21c84d32827518c5/src/js/components/core/CheckDataGrabber.js#L37)):_

> ``` JavaScript
>     }
>   },
>   onComplete: function(err, data) {
> ```

This is fine for now but if we are passing errors into a function consider a try catch block in the future. You are essentially doing a weird try catch block here anyway.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107)_

**Comment by ihoegen** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 31 unresolved discussions, some commit checks failed.

---

_[check_data.json, line 0 [r4]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KN2aR-ooGR99GfGEpVy:-KN2aR-pBgdmD5Ud8Z2k:-1943288989) ([raw file](https://github.com/wycliffeassociates/8woc/blob/28dab1eba7377987bc6f4a29eda58628653b2cba/check_data.json#L0)):_
Delete this and add check_data.json to the git ignore so I never have to see it again

---

_[src/js/components/core/ChangesReportSaver.js, line 11 [r4]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KN2axKGs6iAdscriL7n:-KN2axKHvpotpv_Axxnw:2039790938) ([raw file](https://github.com/wycliffeassociates/8woc/blob/28dab1eba7377987bc6f4a29eda58628653b2cba/src/js/components/core/ChangesReportSaver.js#L11)):_

> ``` JavaScript
>     //creates folder path for only folders that need to be created
>     fs.outputJson(filepath, report, function (err) {
>       console.log(err) // => null
> ```

Should only log the error if the error is not null. Also, what happens if the file already exists?

---

_[src/js/components/core/CreateNewProject.js, line 22 [r4]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KN2bHsadypVbVr8zwWq:-KN2bHsbmHe_k-2-4N_v:-1006182866) ([raw file](https://github.com/wycliffeassociates/8woc/blob/28dab1eba7377987bc6f4a29eda58628653b2cba/src/js/components/core/CreateNewProject.js#L22)):_

> ``` JavaScript
>     try {
>       var file = fs.readdirSync(window.__base + 'src/js/components/modules');
>       for (var element of file) {
> ```

Why would you use `of` instead of `in`?

---

_[src/js/components/modules/lexical_check_module/lexical_checker/Door43DataFetcher.js, line 116 [r4]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107#-KN2bX9BMcSWs4LfEwPX:-KN2bX9BMcSWs4LfEwPY:-537536048) ([raw file](https://github.com/wycliffeassociates/8woc/blob/28dab1eba7377987bc6f4a29eda58628653b2cba/src/js/components/modules/lexical_check_module/lexical_checker/Door43DataFetcher.js#L116)):_

> ``` JavaScript
>                                           for (let _chapter of bookObj['chapters']) {
>                                               let verses = [];
>                                               let totalChapterVerses = _chapter['verses'].length;
> ```

This file indentation is awful. Someone please fix this

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107)_

**Comment by mannycolon** [comment]
Reviewed 4 of 13 files at r1, 3 of 12 files at r2, 1 of 2 files at r3, 5 of 6 files at r5, 220 of 220 files at r6.
Review status: all files reviewed at latest revision, 31 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/107)_

**Pull request merged**
