### PR TITLE
Sf lexical check

### PR DESCRIPTION
**Pull request by therealsamf**
I added lexical check and the FetchData and CheckModule and ReportView

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/92)

### CODE REVIEW

**Comment by vleong2332** [comment]
@therealsamf, I think I saw a couple of recent changes got reverted by your branch. Could you make sure that you updated your local develop, merged that to your branch, fixed any conflict, and pushed to this branch again?

**Comment by vleong2332** [comment]
Reviewed 2 of 30 files at r1, 4 of 47 files at r9, 2 of 12 files at r10.
Review status: 8 of 33 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_[.babelrc, line 2 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMQZOQeCtEITcw0kM9h:-KMQZOQeCtEITcw0kM9i:-2133772269) ([raw file](https://github.com/wycliffeassociates/8woc/blob/0237a91eaf54cbca4c15c6f197ded1a90d6698e0/.babelrc#L2)):_

> ```
> {
>   "presets": ["react"]
> ```

Could you convert the tabs into spaces?

---

_[index.html, line 8 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUOVZrdfWc1S77bhe9:-KMUOVZsoy9qNtIbeYQP:-501200462) ([raw file](https://github.com/wycliffeassociates/8woc/blob/d6a9166ad07a46ffb7eafbcc553e98140c0b0d0a/index.html#L8)):_

> ``` HTML
>     <link rel="stylesheet" href="node_modules\bootstrap\dist\css\bootstrap.min.css" />
>     <link rel="stylesheet" href="node_modules\bootstrap\dist\css\bootstrap-theme.min.css" />
>     <link rel="stylesheet" type="text/css" href="src\css\stylesheet.css">
> ```

Why are the meta and links removed?

---

_[src/js/components/modules/lexical_check_module/CheckModuleView.js, line 1 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUOh9PXvtTtrGaioOQ:-KMUOh9PXvtTtrGaioOR:1274228679) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/CheckModuleView.js#L1)):_

> ``` JavaScript
> //CheckModuleView.js//
> ```

This comment seems unnecessary. Don't have to fix if file is temporary.

---

_[src/js/components/modules/lexical_check_module/CheckModuleView.js, line 21 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUOmmhKcCus8MJ9DYT:-KMUOmmhKcCus8MJ9DYU:780491382) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/CheckModuleView.js#L21)):_

> ``` JavaScript
> const LexicalCheckModule = React.createClass({
> 
>   componentWillMount: function() {
> ```

Convert tabs to spaces. Don't have to fix if file is temporary.

---

_[src/js/components/modules/lexical_check_module/CheckModuleView.js, line 26 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUOpXUk2RQCNwayaq8:-KMUOpXVAnkXb8M3tUQ0:664903252) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/CheckModuleView.js#L26)):_

> ``` JavaScript
> 
>   componentWillUnmount: function() {
> 
> ```

Remove spaces on a blank line. Don't have to fix if file is temporary.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92)_

**Comment by vleong2332** [comment]
Reviewed 13 of 47 files at r9, 3 of 13 files at r10, 8 of 13 files at r11, 33 of 37 files at r12.
Review status: 46 of 57 files reviewed at latest revision, 46 unresolved discussions, some commit checks failed.

---

_[.config, line 1 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVCYMHTPU1GFOppLaI:-KMVCYMI_NYR9uhmth28:168090562) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/.config#L1)):_

> ```
> 8855fed6cfc489db14b52c5ad17612b67508471c
> ```

What is this?

---

_[src/js/components/core/AuthToken.js, line 2 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVCnJ0wcebtEloQ5Ht:-KMVCnJ0wcebtEloQ5Hu:399561831) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/core/AuthToken.js#L2)):_

> ``` JavaScript
> const FileModule = require('./FileModule');
> ```

Trailing space

---

_[src/js/components/core/AuthToken.js, line 4 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVCpdYNdWI1GlDDEnb:-KMVCpdYNdWI1GlDDEnc:-1137758057) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/core/AuthToken.js#L4)):_

> ``` JavaScript
> 
> FileModule.readFile('.config', function(data){
>   module.exports = {
> ```

Tabs. Trailing space.

---

_[src/js/components/core/GogsApi.js, line 2 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVCwqbbxn0Cf8PxtA8:-KMVCwqbbxn0Cf8PxtA9:-1638909614) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/core/GogsApi.js#L2)):_

> ``` JavaScript
> Gogs = require('gogs-client');
> var api = new Gogs('https://git.door43.org/api/v1'), tokenStub = {name: 'translation-core'};
> ```

Put `tokenStub` on its own line. You can keep the comma, but indent `tokenStub` to align with `api`.

---

_[src/js/components/modules/lexical_check_module/CheckModuleView.js, line 46 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVDg0BsgtoBPHYMt4U:-KMVDg0BsgtoBPHYMt4V:-37538747) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/lexical_check_module/CheckModuleView.js#L46)):_

> ``` JavaScript
>       return (
>           <div>
> 
> ```

Just an empty div?

---

_[src/js/components/modules/lexical_check_module/FetchData.js, line 1 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUPFaJXZjsGIc03IsM:-KMUPFaJXZjsGIc03IsN:-1868908035) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/FetchData.js#L1)):_

> ``` JavaScript
> //FetchData.js//
> ```

This comment seems unnecessary.

---

_[src/js/components/modules/lexical_check_module/FetchData.js, line 25 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUPIi98QnJeK64_EkB:-KMUPIiATmkHbIfn8lbO:1321916185) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/FetchData.js#L25)):_

> ``` JavaScript
>  */
> function getData(bookAbbr, progressCallback, callback) {
>   //Get Bible
> ```

Tabs to spaces.

---

_[src/js/components/modules/lexical_check_module/FetchData.js, line 29 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUPRsNMvPRqrCLBQdi:-KMUPRsNMvPRqrCLBQdj:-1191032094) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/FetchData.js#L29)):_

> ``` JavaScript
>   var Door43Fetcher = new Door43DataFetcher();
>   Door43Fetcher.getBook(bookAbbr, function(done, total) {
>           progressCallback((done / total) * 0.5)}, function(error, data) {
> ```

What's the 0.5?

---

_[src/js/components/modules/lexical_check_module/FetchData.js, line 41 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUPa7KN5QcSXYVA3Bf:-KMUPa7KN5QcSXYVA3Bg:-412201408) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/FetchData.js#L41)):_

> ``` JavaScript
>           var wordList;
>           tWFetcher.getWordList(undefined, 
>               function(error, data) {
> ```

If `function()` is part of the argument for `getWordList()`, you may write it on the same line as `undefined`, like you did with `getBook()` above. That will cut down on the number of indentations for the rest of the file.

---

_[src/js/components/modules/lexical_check_module/FetchData.js, line 166 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUQF3W7ZNiHzoYFyGd:-KMUQF3X_8o2k7g3MOUb:1247448861) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/FetchData.js#L166)):_

> ``` JavaScript
> }
> 
> module.exports = getData;
> ```

So, if you want to export just `getData()`, and if the rest are helper functions, a better way to write it is this...

```
const Dep = require('dependencies');

module.exports = function() {

   const protectedVariable = value;

   function helperFunction() {
      // ...
   }

   return function() {
      // Definition of getData()
      // Use protectedVariable and helperFunction here.
   }

}();
```

---

_[src/js/components/modules/lexical_check_module/ReportView.js, line 11 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUSMuBAOA9hPupvJdW:-KMUSMuBAOA9hPupvJdX:-1927829517) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/ReportView.js#L11)):_

> ``` JavaScript
> 
>  const LexicalReportView = React.createClass({
> ```

Intentionally empty?

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 17 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUSS-u5Bc00Cs1FR_-:-KMUSS-u5Bc00Cs1FR_0:1321916185) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L17)):_

> ``` JavaScript
> const REPLACE_TEXT = "Replace";
> const RETAIN_TEXT = "Retain";
> 
> ```

Tabs to spaces.

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 19 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUSTOtxyaY3SdTZMdY:-KMUSTOtxyaY3SdTZMdZ:-1426590284) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L19)):_

> ``` JavaScript
> 
> const LexicalChecker = React.createClass({
> 
> ```

Spaces on empty line.

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 50 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUScsZB32kPX-LbY9p:-KMUScsZB32kPX-LbY9q:968297572) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L50)):_

> ``` JavaScript
>   var _this = this;
>   this.htmlScraper.downloadEntireBook('1ch',
>                       function(done, max) { //progressCallback
> ```

You can just indent this one level deeper than the line above it. Or better yet, extract the define the callback functions outside.

```
function progressCallback() {...}
function doneCallback() {...}

this.htmlScraper.downloadEntireBook('1ch', progressCallback, doneCallback);
```

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 61 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUTEAwfyxSNivF8dE6:-KMUTEAwfyxSNivF8dE7:-958206678) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L61)):_

> ``` JavaScript
> 
>     submitWords: function() { //retain button callback
>   var words = this.refs.targetLanguageBox.getWords();
> ```

Indentation.

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 80 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUTJAFDTt596KSpbtW:-KMUTJAFDTt596KSpbtX:1283306981) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L80)):_

> ``` JavaScript
>       if (this.refs.customButtonGroup) {
>           this.refs.customButtonGroup.enableButtons();
>       }
> ```

I notice that there are a lot of callbacks. Is there a better way to do what you're trying to do?

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 85 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUTPx-wXR1X8e2JuGR:-KMUTPx-wXR1X8e2JuGS:436496902) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L85)):_

> ``` JavaScript
> 
> //Contains the word being defined and the definition of the word
> var Definition = React.createClass({
> ```

This should be written as a separate component that's imported here.

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 94 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUTWpTtsPwGyN4Ejao:-KMUTWpUko_i8XRc5gS4:436496902) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L94)):_

> ``` JavaScript
> 
> /* Contains a word from the target language, defines a lot of listeners for clicks */
> var TargetWord = React.createClass({
> ```

This should be written as a separate component that's imported here.

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 118 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUT_lkw9qj-TldUYL2:-KMUT_lkw9qj-TldUYL3:-991755330) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L118)):_

> ``` JavaScript
>           this.props.removeCallback(this.state.wordObj);
>       }
>       this.setState({highlighted: !this.state.highlighted}); //this sets React to re-render the component
> ```

As a general rule, let's put comments on their own lines above the code that they comment on.

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 130 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUTkUy_plyLY0iEaTT:-KMUTkUy_plyLY0iEaTU:1471980976) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L130)):_

> ``` JavaScript
>       // else {
>       //  this.props.removeCallback(this.state.wordObj);
>       // }
> ```

If not needed anymore, these should be removed.

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 132 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUTof4JTQ5jYomEfUT:-KMUTof4JTQ5jYomEfUU:674189342) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L132)):_

> ``` JavaScript
>       // }
> 
>       return (<span 
> ```

```
return(
   <span>
   </span>
);
```

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 143 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUTxjc2PfKcDdXXo8Y:-KMUTxjc2PfKcDdXXo8Z:436496902) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L143)):_

> ``` JavaScript
> });
> 
> var TargetLanguageSelectBox = React.createClass({
> ```

This should be written as a separate component that's imported here.

---

_[src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js, line 237 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUUDuNOShQ7cQGyBSV:-KMUUDuO9gk7E6XgFTcL:436496902) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/lexical_checker/LexicalChecker.js#L237)):_

> ``` JavaScript
> });
> 
> var CustomButtonGroup = React.createClass({
> ```

This should be written as a separate component that's imported here.

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js, line 66 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUXfxaN8EnXAnhYACe:-KMUXfxaN8EnXAnhYACf:164585967) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js#L66)):_

> ``` JavaScript
>                   <Modal.Title>
>                       <span>
>                           <Glyphicon
> ```

The `Glyphicon` element is short enough to be put in one line.

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js, line 104 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUY-IwiRosQxds22aL:-KMUY-IwiRosQxds22aM:1008870944) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js#L104)):_

> ``` JavaScript
>           function() { //errorCallback
>               console.error('Words Scraper failed');
>               _this.modalClosed(); /* we're going to put up another modal
> ```

All comments need to follow JSDoc convention.

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js, line 123 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUY8eqFFidhqsR8B7q:-KMUY8eqFFidhqsR8B7r:-1106241738) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js#L123)):_

> ``` JavaScript
>                       title={UNABLE_TO_GET_WORDS_TITLE}
>                       closeCallback={
>                           function() {
> ```

If possible, let's define the functions outside the attribute assignment.

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js, line 168 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUYQMaX791mSM7kCX6:-KMUYQMaX791mSM7kCX7:1846633236) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js#L168)):_

> ``` JavaScript
>                   <form
>                       onSubmit={function(e) {
>                           e.preventDefault();
> ```

Same thing. Define the function outside if possible.

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js, line 173 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMUYZffHLq1uhiC_x74:-KMUYZffHLq1uhiC_x75:-2103491903) ([raw file](https://github.com/wycliffeassociates/8woc/blob/21ebea67a8d333e531885c4a9733763d39bc8684/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsDisplay.js#L173)):_

> ``` JavaScript
>                       }}
>                   >
>                       <FormGroup
> ```

One line for `FormGroup`

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsFetcher.js, line 10 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVDkAQuHaPQgKvWA9F:-KMVDkAQuHaPQgKvWA9G:-484797845) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsFetcher.js#L10)):_

> ``` JavaScript
> 
> const GITHUB_API_URL = "https://api.github.com/repos/Door43/d43-en/contents/obe?ref=master",
>   REQUEST_FAILED = "Request failed",
> ```

Tabs.

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js, line 18 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVDxLNqbmMu_8YISLD:-KMVDxLNqbmMu_8YISLE:677098019) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js#L18)):_

> ``` JavaScript
> 
> class TranslationWordsScraper {
>   constructor () {
> ```

Tabs

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js, line 33 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVDzahUst3nnnVOwXM:-KMVDzahUst3nnnVOwXN:1049320839) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js#L33)):_

> ``` JavaScript
>       if (this.wordList) {
>           Fs.outputJson(path, this.wordList, 
>               function(error) {
> ```

Put opening function on the same line with the other params.

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js, line 80 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVE7mJ6ZJENRTt_fsG:-KMVE7mJ6ZJENRTt_fsH:1970379276) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js#L80)):_

> ``` JavaScript
>       request.open('get', url, true);
>       request.send();
>       }
> ```

There's something wrong with the indentation here.

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js, line 96 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVEI--7FPVREU9G1gv:-KMVEI--7FPVREU9G1gw:-1832025212) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js#L96)):_

> ``` JavaScript
>       // }
>       // else {
>           var _this = this;
> ```

Indentation

---

_[src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js, line 124 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVEKtp-xTmAyqZSwVI:-KMVEKtp-xTmAyqZSwVJ:-498485012) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/lexical_check_module/translation_words/TranslationWordsScraper.js#L124)):_

> ``` JavaScript
> 
> function getItemsBehindLink(htmlString) {
> 
> ```

Trailing spaces

---

_[src/js/components/modules/lexical_check_module/translation_words/WordTesterScript.js, line 58 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVE_GoA4U37by4RdlZ:-KMVE_GoA4U37by4Rdl_:139351585) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/lexical_check_module/translation_words/WordTesterScript.js#L58)):_

> ``` JavaScript
> }
> 
> module.exports = testBook;
> ```

Put this in a closure.

---

_[src/js/components/modules/phrase_check_module/FetchData.js, line 12 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVF6dWR6tnio7VrNBc:-KMVF6dWR6tnio7VrNBd:641573436) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/phrase_check_module/FetchData.js#L12)):_

> ``` JavaScript
>     bookAbbr,
>     function(done, total){
>       progress(done/total*100);
> ```

Could you define these functions outside?

---

_[src/js/components/modules/phrase_check_module/parsers/Door43DataFetcher.js, line 14 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVFCM9OXEx21wBlz0Q:-KMVFCM9OXEx21wBlz0R:677098019) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/phrase_check_module/parsers/Door43DataFetcher.js#L14)):_

> ``` JavaScript
>  //hardcoded github api calls
>  const GITHUB_API_NOTES = "https://api.github.com/repositories/23808509/contents/bible/notes",
>   INVALID_DATA = "Invalid Data",
> ```

Tabs

---

_[src/js/components/modules/phrase_check_module/parsers/Door43DataFetcher.js, line 139 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVFlHptgOABQcsBzcS:-KMVFlHptgOABQcsBzcT:1937226727) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/phrase_check_module/parsers/Door43DataFetcher.js#L139)):_

> ``` JavaScript
>                                                               if (numVerses >= totalVerses) {
>                                                                   callback(null, bookObj);
>                                                               }
> ```

This is what is defined as callback hell. That makes this file extremely difficult to review. Could you refactor this? 

---

_[src/js/components/modules/translation_notes/ErrorModal.js, line 25 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVHB7u_XkxFuHlm-pv:-KMVHB7v8R5nFnpMFrcH:677098019) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/translation_notes/ErrorModal.js#L25)):_

> ``` JavaScript
> */
> const ErrorModal = React.createClass({
>   getInitialState: function() {
> ```

Tabs

---

_[src/js/components/modules/translation_notes/FileUploader.js, line 27 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVHGDeoZCJ8JYEUjDE:-KMVHGDeoZCJ8JYEUjDF:677098019) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/translation_notes/FileUploader.js#L27)):_

> ``` JavaScript
> const FileUploader = React.createClass({
> 
>   getInitialState: function() {
> ```

Tabs

---

_[src/js/components/modules/translation_notes/FileUploader.js, line 50 [r12]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92#-KMVHLv_n5KTRX_NL4f6:-KMVHLv_n5KTRX_NL4f7:-717392753) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7709c11c15fc936dd8a09b7cf3fcae6f270f0e13/src/js/components/modules/translation_notes/FileUploader.js#L50)):_

> ``` JavaScript
>       onClick: function() {
>           var _this = this;
>       dialog.showOpenDialog(
> ```

Tabs. Indentations.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/92)_

**Comment by ihoegen** [comment]
Fix Vicky's suggestions and make it merge friendly, and I'll review it

**Pull request merged**
