### PR TITLE
added new logo and fixed styling on sidebar

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/326)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/SideBar/Style.js, line 37 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/326#-KOffghfhgN5MID8D_OC:-KOffghgpkKvINPqDQtx:b-16q2cm) ([raw file](https://github.com/wycliffeassociates/8woc/blob/44791fb186b48c4c28e88be1726c30edabe966eb/src/js/components/core/SideBar/Style.js#L37)):_

> ``` JavaScript
>   glyphiconHover: {
>     fontSize: "29px",
>     color: "#c11525",
> ```

I'm not a fan of the red. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/326)_

**Comment by mannycolon** [comment]
the red color was suggested by the designers

**Comment by ihoegen** [comment]
Shoot, I actually have to do it then. I prefered the blue, anyone else have thoughts on it?

**Comment by EvanWiederspan** [comment]
ya why red? its kinda menacing

**Comment by mannycolon** [comment]
I changed the hover color to blue, the red was suggested by the designers

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/js/components/core/SideBar/Style.js, line 41 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/326#-KOkETNXfTrYNpPtsoi-:-KOkETNYFfnT2Rm1ZlfS:b-yzg9xl) ([raw file](https://github.com/wycliffeassociates/8woc/blob/46da3fe684afab2cba80d655b841c67b725acafe/src/js/components/core/SideBar/Style.js#L41)):_

> #39add2

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/326)_

**Pull request merged**
