### PR TITLE
Converted the action constants to enum style

### PR DESCRIPTION
**Pull request by lancelebanoff**
Instead of a map of (string -> string), now we're using (field -> string)

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/78)

### CODE REVIEW

**Comment by ihoegen** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/actions/CoreActionConsts.js, line 9 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/78#-KM519IzKIxhIoNEHWyF:-KM519J-gfK-12ZNVdmz:1979763966) ([raw file](https://github.com/wycliffeassociates/8woc/blob/d24d9dc794f01ab69dd44ed32e535241178ff386/src/js/actions/CoreActionConsts.js#L9)):_

> ``` JavaScript
>   UPDATE_GATEWAY_LANGUAGE: "UPDATE_GATEWAY_LANGUAGE",
>   CHANGE_UPLOAD_MODAL_VISIBILITY: "CHANGE_UPLOAD_MODAL_VISIBILITY",
>   CHANGE_CHECK_TYPE: "CHANGE_CHECK_TYPE",
> ```

Could I ask why this was done?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/78)_

**Comment by vleong2332** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/js/actions/CoreActionConsts.js, line 9 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/78#-KM519IzKIxhIoNEHWyF:-KM5KICmvZGR-hocOmDI:171906464) ([raw file](https://github.com/wycliffeassociates/8woc/blob/d24d9dc794f01ab69dd44ed32e535241178ff386/src/js/actions/CoreActionConsts.js#L9)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> Could I ask why this was done?
> </details>
> I think in the spirit of constants, the way to refer it will be `consts.ADD_CHECK` instead of `consts['AddCheck']` which looks better to me.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/78)_

**Comment by vleong2332** [comment]
@lancelebanoff, looks good to me, but there's a merge conflict. Please update your develop and merge, then update this PR again.

**Comment by vleong2332** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/78)_

**Pull request merged**
