### PR TITLE
NavBar/Login modal integration with develop

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/85)

### CODE REVIEW

**Comment by vleong2332** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/js/components/LoginModal.js, line 20 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KM9ofK5Gdy_FAEWRbMb:-KM9ofK6sexzQM1lli3M:1940155791) ([raw file](https://github.com/wycliffeassociates/8woc/blob/88487141cbce903a5f09f9409a0d0faecfef9584/src/js/components/LoginModal.js#L20)):_

> ``` JavaScript
>     componentWillMount() {
>       CoreStore.addChangeListener(this.updateLoginModal.bind(this));
>     }
> ```

You probably want to also `removeChangeListener()` on `componentWillUnmount()` to avoid memory leak.

---

_[src/js/components/Toggle.js, line 17 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KM9pEluD_R71yhYOPNq:-KM9pEluD_R71yhYOPNr:-1832025212) ([raw file](https://github.com/wycliffeassociates/8woc/blob/88487141cbce903a5f09f9409a0d0faecfef9584/src/js/components/Toggle.js#L17)):_

> ``` JavaScript
>   handleClick(){
>     if(this.state.online == false){
>     CoreActions.updateLoginModal(true);
> ```

Indentation

---

_[src/js/styles/loginStyle.js, line 6 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KM9pR5K_eJB_CM9fCEv:-KM9pR5K_eJB_CM9fCEw:1438318183) ([raw file](https://github.com/wycliffeassociates/8woc/blob/88487141cbce903a5f09f9409a0d0faecfef9584/src/js/styles/loginStyle.js#L6)):_

> ``` JavaScript
>         margin: '12px'
>       }
>   },//close loginbox selector
> ```

Let's put comments on the line above the code that it comments on.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85)_

**Comment by vleong2332** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[src/js/components/LoginModal.js, line 21 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KMAtKZqaACoZ7x99YgM:-KMAtKZqaACoZ7x99YgN:1883765765) ([raw file](https://github.com/wycliffeassociates/8woc/blob/430482b77ca4ae9195275fa8ac012b54bb7e255c/src/js/components/LoginModal.js#L21)):_

> ``` JavaScript
>       CoreStore.addChangeListener(this.updateLoginModal.bind(this));
>     }
> 
> ```

Empty spaces

---

_[src/js/styles/loginStyle.js, line 22 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KMAtNO1lQwLsjblvA5C:-KMAtNO1lQwLsjblvA5D:-1391342301) ([raw file](https://github.com/wycliffeassociates/8woc/blob/430482b77ca4ae9195275fa8ac012b54bb7e255c/src/js/styles/loginStyle.js#L22)):_

> ``` JavaScript
> NavBarbutton:{
>   marginTop: "10px",
> },
> ```

From `logo` to here has wrong indentation.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85)_

**Comment by mannycolon** [comment]
Review status: 7 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_[src/js/components/LoginModal.js, line 20 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KM9ofK5Gdy_FAEWRbMb:-KMB-XiqLAGmRkbfCBQ8:-499146009) ([raw file](https://github.com/wycliffeassociates/8woc/blob/88487141cbce903a5f09f9409a0d0faecfef9584/src/js/components/LoginModal.js#L20)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> You probably want to also `removeChangeListener()` on `componentWillUnmount()` to avoid memory leak.
> </details>
> Done.

---

_[src/js/components/LoginModal.js, line 21 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KMAtKZqaACoZ7x99YgM:-KMB-YUvF1MhM2w_m8mL:-499146009) ([raw file](https://github.com/wycliffeassociates/8woc/blob/430482b77ca4ae9195275fa8ac012b54bb7e255c/src/js/components/LoginModal.js#L21)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Empty spaces
> </details>
> Done.

---

_[src/js/components/Toggle.js, line 17 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KM9pEluD_R71yhYOPNq:-KMB-ZEam5Mqcti78Ak1:-499146009) ([raw file](https://github.com/wycliffeassociates/8woc/blob/88487141cbce903a5f09f9409a0d0faecfef9584/src/js/components/Toggle.js#L17)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Indentation
> </details>
> Done.

---

_[src/js/styles/loginStyle.js, line 6 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KM9pR5K_eJB_CM9fCEv:-KMB-Zx8HmLI90TZwyTT:-499146009) ([raw file](https://github.com/wycliffeassociates/8woc/blob/88487141cbce903a5f09f9409a0d0faecfef9584/src/js/styles/loginStyle.js#L6)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Let's put comments on the line above the code that it comments on.
> </details>
> Done.

---

_[src/js/styles/loginStyle.js, line 22 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85#-KMAtNO1lQwLsjblvA5C:-KMB-_fjJKP-82qTjp9Q:-499146009) ([raw file](https://github.com/wycliffeassociates/8woc/blob/430482b77ca4ae9195275fa8ac012b54bb7e255c/src/js/styles/loginStyle.js#L22)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> From `logo` to here has wrong indentation.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85)_

**Comment by vleong2332** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85)_

**Comment by vleong2332** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/85)_

**Pull request merged**
