### PR TITLE
I added alerts with console logs

### PR DESCRIPTION
**Pull request by RoyalSix**
some of these may be removed by popovers

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/310)

### CODE REVIEW

**Comment by loganlebanoff** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/js/components/core/AccessProject.js, line 37 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/310#-KOFvlKTK7qQYPyHPidv:-KOFvlKTK7qQYPyHPidw:517109010) ([raw file](https://github.com/wycliffeassociates/8woc/blob/bd5e3df2a9a4969d13cc5428c3e64d06c01d4435/src/js/components/core/AccessProject.js#L37)):_

> ``` JavaScript
>       });
>     } catch (e) {
>       console.error(e);
> ```

Is it redundant to keep the console.errors? I guess the console errors are nice because they tell the stack trace and line number of the error so never mind. I guess this is ok.

---

_[src/js/components/core/BooksOfBible.js, line 5 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/310#-KOFvJrgtkwwERj9KQZA:-KOFvJrgtkwwERj9KQZB:-2046261683) ([raw file](https://github.com/wycliffeassociates/8woc/blob/bd5e3df2a9a4969d13cc5428c3e64d06c01d4435/src/js/components/core/BooksOfBible.js#L5)):_

> ``` JavaScript
>    * code and binary search the tree of values from highest to lowest into a node package of bible names
>    * @author - RoyalSix
>    **/
> ```

HAHAHAHA I am literally dying. I approve.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/310)_

**Comment by loganlebanoff** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/js/components/core/LoadOnline.js, line 68 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/310#-KOFy4Ep8oU8ZPKh06kW:-KOFy4Ep8oU8ZPKh06kX:-855306046) ([raw file](https://github.com/wycliffeassociates/8woc/blob/bd5e3df2a9a4969d13cc5428c3e64d06c01d4435/src/js/components/core/LoadOnline.js#L68)):_

> ``` JavaScript
>       } catch (error) {
>           const alert = {
>             title: 'Warning',
> ```

Title is just "warning"?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/310)_

**Comment by RoyalSix** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/js/components/core/LoadOnline.js, line 68 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/310#-KOFy4Ep8oU8ZPKh06kW:-KOG28SU1qtN2d475vt1:-249639456) ([raw file](https://github.com/wycliffeassociates/8woc/blob/bd5e3df2a9a4969d13cc5428c3e64d06c01d4435/src/js/components/core/LoadOnline.js#L68)):_
<details><summary>

<i>Previously, loganlebanoff (Logan Thien Lebanoff) wrote…</i></summary>



> Title is just "warning"?
> </details>
> this title for this one 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/310)_

**Comment by loganlebanoff** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/310)_

**Comment by therealsamf** [comment]
bro....

**Pull request closed without merging**
