### PR TITLE
Add triple pane view along with modal for upload

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/22)

### CODE REVIEW

**Comment by ihoegen** [comment]
Fixing merge conflicts now

**Comment by vleong2332** [comment]
Reviewed 13 of 15 files at r1, 5 of 6 files at r2.
Review status: 13 of 15 files reviewed at latest revision, 14 unresolved discussions.

---

_[src/js/FileActions.js, line 23 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWU0fRaH-H93fjtxfI:-KLWU0fRaH-H93fjtxfJ:923844559) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/FileActions.js#L23)):_

> ``` JavaScript
>     this.open = boolean;
>     this.emit("upload", this.open);
>   }
> ```

Is `this.open` needed anywhere else? It seems like you're keeping a state of `open`, but `setState()` just pass it through to `this.emit()` If `this.open` is not used/referred-to anywhere else, you can remove it and do `this.emit('upload', boolean);`. If it is, then ignore this comment.

---

_[src/js/fileupload.js, line 12 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWXG7RaXxgxwFNA4aU:-KLWXG7RaXxgxwFNA4aV:-272541902) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L12)):_

> ``` JavaScript
> const {dialog} = remote;
> const React = require('react');
> const TPane = require('./tpane');
> ```

Is `fileupload` the parent component of `tpane`? `tpane` is also included in `index.js`. Is the app going to have multiple instances of `tpane`?

---

_[src/js/fileupload.js, line 79 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWVKIqnVwDtW5CLW6H:-KLWVKIqnVwDtW5CLW6I:-1014892346) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L79)):_

> ``` JavaScript
> function sendToReader(file) {
>   try {
>     window.manifestSource = file;
> ```

For this and the following lines where `window` is used: Are these variable suppose to be global? Is there another solution to keep track of these variables instead of making them global?

---

_[src/js/fileupload.js, line 95 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWW22FqXrj_YfyJ52h:-KLWW22FqXrj_YfyJ52i:-189593077) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L95)):_

> ``` JavaScript
>   let parsedManifest = JSON.parse(manifest);
>   let finishedChunks = parsedManifest.finished_chunks;
>   window.joinedChunks = {};
> ```

See above

---

_[src/js/fileupload.js, line 103 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWW4tNekZ6Pz0YPAMR:-KLWW4tNekZ6Pz0YPAMS:-189593077) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L103)):_

> ``` JavaScript
>   }
> 
>   var textInput = window.joinedChunks;
> ```

See above

---

_[src/js/fileupload.js, line 112 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWW7wMbfUwsSUttz0I:-KLWW7wMbfUwsSUttz0J:-189593077) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L112)):_

> ``` JavaScript
> function openUsfmFromChunks(chunk) {
>   var source = window.manifestSource;
>   window.currentChapter = chunk[0];
> ```

See above

---

_[src/js/fileupload.js, line 127 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWWAfK_vidFWpyuJR3:-KLWWAfK_vidFWpyuJR4:-189593077) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L127)):_

> ``` JavaScript
> function saveChunksLocal(text) {
>   var currentJoined = window.joinedChunks;
>   var currentChapter = window.currentChapter;
> ```

See above

---

_[src/js/fileupload.js, line 142 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWWF2E46gH3Xx6FOLN:-KLWWF2E46gH3Xx6FOLO:-189593077) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L142)):_

> ``` JavaScript
>     }
>   }
>   window.joinedChunks = currentJoined;
> ```

See above

---

_[src/js/fileupload.js, line 153 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWWIzeYL85lnosBcUU:-KLWWIzeYL85lnosBcUV:-937976774) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L153)):_

> ``` JavaScript
>   );
>   }
> });
> ```

If `Verse` is going to be used for real (not just for the demo), let's put that in a separate JS file and export it as a module.

---

_[src/js/fileupload.js, line 164 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWWepfloN3hCR8QIDv:-KLWWepgIyt2VHyv7zez:1278583399) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L164)):_

> ``` JavaScript
>   );
>   }
> });
> ```

See the note for `Verse`

---

_[src/js/fileupload.js, line 171 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWWjCxTo53aeH-4K1X:-KLWWjCxTo53aeH-4K1Y:1278583399) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L171)):_

> ``` JavaScript
>   );
>   }
> });
> ```

See the note for `Verse`

---

_[src/js/fileupload.js, line 200 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWWo__byWNDWhIMVQG:-KLWWo_aHSwRol-Sppot:1278583399) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/fileupload.js#L200)):_

> ``` JavaScript
>       );
>   }
> });
> ```

See the note for `Verse`

---

_[src/js/index.js, line 23 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWX1my8eDByb4MiJRt:-KLWX1my8eDByb4MiJRu:-695184530) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/index.js#L23)):_

> ``` JavaScript
>         </div>
>       );
>       ReactDOM.render(Application, document.getElementById('content'));
> ```

Are these elements shown for the real app or just for the demo?

---

_[src/js/tpane.js, line 36 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22#-KLWYEHoqpHpE6e89BKC:-KLWYEHoqpHpE6e89BKD:-1331047365) ([raw file](https://github.com/wycliffeassociates/8woc/blob/76fcf59e70155d491be8bbd4c6ad1eb1f85b6446/src/js/tpane.js#L36)):_

> ``` JavaScript
>   }
> 
> });
> ```

`Pane` can go into a separate file and exported here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22)_

**Comment by vleong2332** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22)_

**Comment by ihoegen** [comment]
The elements shown there are just for a demo but can be used for the real app

**Comment by vleong2332** [comment]
Reviewed 1 of 6 files at r2, 11 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/22)_

**Pull request merged**
