### PR TITLE
Rework the file upload

### PR DESCRIPTION
**Pull request by ihoegen**
This branch redos the the import from online, and also modularized the file import functions.

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/124)

### CODE REVIEW

**Comment by loganlebanoff** [comment]
Reviewed 234 of 235 files at r1, 127 of 127 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[gulpfile.js, line 0 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2Z2ZzjBfAqGrRwLlL:-KN2Z2ZzjBfAqGrRwLlM:674539826) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/gulpfile.js#L0)):_
We want to delete the gulpfile? I guess we might as well, just making sure.

---

_[requirements.js, line 4 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2ZSynhpADGdKsP-Rz:-KN2ZSynhpADGdKsP-S-:1531591652) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/requirements.js#L4)):_

> ``` JavaScript
> window.__base = __dirname + '/';
> window.zip = require('adm-zip');
> window.downloadModule = require('download');
> ```

Should these be global?

---

_[src/js/actions/Deletefolder.js, line 20 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2bouEL8HnIXOc6Z8e:-KN2bouEL8HnIXOc6Z8f:-1495438541) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/src/js/actions/Deletefolder.js#L20)):_

> ``` JavaScript
> 
> var newpath = path.join('**');
> del.sync([newpath, '!*.js']);
> ```

Does this file belong in /actions?

---

_[src/js/actions/Recieverepo.js, line 55 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2byIUQgUQZoi5uljg:-KN2byIUQgUQZoi5uljh:-1495438541) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/src/js/actions/Recieverepo.js#L55)):_

> ``` JavaScript
>   //   console.log("...");
>   // });
> });
> ```

Does this file belong in /actions?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124)_

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[gulpfile.js, line  [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2Z2ZzjBfAqGrRwLlL:-KN2fEPzkSPn0VTtP-Ix:-1220516523) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/gulpfile.js#L)):_
<details><summary>

<i>Previously, loganlebanoff (Logan Thien Lebanoff) wrote…</i></summary>



> We want to delete the gulpfile? I guess we might as well, just making sure.
> </details>
> Yep, this is on porpoise. 

---

_[requirements.js, line 4 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2ZSynhpADGdKsP-Rz:-KN2fJVVIZHJ0AfgoNtQ:-1792369171) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/requirements.js#L4)):_
<details><summary>

<i>Previously, loganlebanoff (Logan Thien Lebanoff) wrote…</i></summary>



> Should these be global?
> </details>
> Yeah these are the modules that for some reason only work when they are top level, so they are made global.

---

_[src/js/actions/Deletefolder.js, line 20 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2bouEL8HnIXOc6Z8e:-KN2fU7GWElYNn5riO5b:-2100212429) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/src/js/actions/Deletefolder.js#L20)):_
<details><summary>

<i>Previously, loganlebanoff (Logan Thien Lebanoff) wrote…</i></summary>



> Does this file belong in /actions?
> </details>
> No clue to this, but it belongs to Greg. Where would you think it goes?

---

_[src/js/actions/Recieverepo.js, line 55 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2byIUQgUQZoi5uljg:-KN2fah-4VpfOLIeq2LS:676771481) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/src/js/actions/Recieverepo.js#L55)):_
<details><summary>

<i>Previously, loganlebanoff (Logan Thien Lebanoff) wrote…</i></summary>



> Does this file belong in /actions?
> </details>
> Ibid

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124)_

**Comment by loganlebanoff** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[src/js/actions/Deletefolder.js, line 20 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2bouEL8HnIXOc6Z8e:-KN2gYUJz88tGr4I6U36:-1745270498) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/src/js/actions/Deletefolder.js#L20)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> No clue to this, but it belongs to Greg. Where would you think it goes?
> </details>
> Probably just put it in /components/core, since everything else similar to this is there.

---

_[src/js/actions/Recieverepo.js, line 55 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124#-KN2byIUQgUQZoi5uljg:-KN2glu7cv7I5160EXgu:-485711229) ([raw file](https://github.com/wycliffeassociates/8woc/blob/286f642712ffe865ccca0b8b61680cd596dccb5a/src/js/actions/Recieverepo.js#L55)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> Ibid
> </details>
> Same.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124)_

**Comment by loganlebanoff** [comment]
Reviewed 4 of 5 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/124)_

**Pull request merged**
