### PR TITLE
Create functionality to load translation studio project from online. 

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/42)

### CODE REVIEW

**Comment by ihoegen** [comment]
Refers to issue #46

**Comment by vleong2332** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/LoadOnline.js, line 20 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0a_YNcZu4N3oPnPAc:-KM0a_YNcZu4N3oPnPAd:-489787444) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/LoadOnline.js#L20)):_

> ``` JavaScript
>   url += '/raw/master/';
>   manifestSource = url;
>   url += 'manifest.json';
> ```

You may want to look at Node's `path` module. Specifically the `join()` to put together a URL. It's better that way because of some OS wanting a `\` and another `/`.

This comment applies to all hard-coded path.

---

_[src/js/components/LoadOnline.js, line 104 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0c7qBs_KSoHqOfMQj:-KM0c7qBs_KSoHqOfMQk:-1679641606) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/LoadOnline.js#L104)):_

> ``` JavaScript
> }
> 
> module.exports = importOnlineProject;
> ```

So it seems like you only want to export one function. I recommend to put it in such format:

```
const = require('deps');

module.exports = (function() {
   var privateVariables;

   function privateFunctions() {}

   function helperFunctions() {}

   return function() {
      // importOnlineProject's content goes here
   }
})();
```

---

_[src/js/components/MenuBar.js, line 80 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0i7NDIT0M5hbLLrSu:-KM0i7NDIT0M5hbLLrSv:968697249) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/MenuBar.js#L80)):_

> ``` JavaScript
>         click() {
>           CoreActions.updateSettings(true);
>         }
> ```

Is this syntax correct?

---

_[src/js/components/OnlineInput.js, line 43 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0iZmRJvXo73UhECyE:-KM0iZmRJvXo73UhECyF:1852341212) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/OnlineInput.js#L43)):_

> ``` JavaScript
>             onChange={this.handleChange}
>             onKeyDown={this.submitViaEnter}
>           />
> ```

Let's put this on one line

---

_[src/js/components/UploadModal.js, line 60 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0iqRkx23wHrn43xGD:-KM0iqRkx23wHrn43xGE:1261047035) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/UploadModal.js#L60)):_

> ``` JavaScript
>           <Nav bsStyle="tabs"
>                activeKey={this.state.active}
>                onSelect={this.handleSelect}>
> ```

One line.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42)_

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/LoadOnline.js, line 20 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0a_YNcZu4N3oPnPAc:-KM4b_GPmDUq5flyLsw9:-499146009) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/LoadOnline.js#L20)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> You may want to look at Node's `path` module. Specifically the `join()` to put together a URL. It's better that way because of some OS wanting a `\` and another `/`.
> 
> This comment applies to all hard-coded path.
> </details>
> Done.

---

_[src/js/components/LoadOnline.js, line 104 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0c7qBs_KSoHqOfMQj:-KM4bbEIT66e7t_xIfne:-499146009) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/LoadOnline.js#L104)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> So it seems like you only want to export one function. I recommend to put it in such format:
> 
> ```
> const = require('deps');
> 
> module.exports = (function() {
>    var privateVariables;
> 
>    function privateFunctions() {}
> 
>    function helperFunctions() {}
> 
>    return function() {
>       // importOnlineProject's content goes here
>    }
> })();
> ```
> 
> </details>
> Done.

---

_[src/js/components/MenuBar.js, line 80 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0i7NDIT0M5hbLLrSu:-KM4bcYcaADsNH1WYWPR:-818693336) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/MenuBar.js#L80)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Is this syntax correct?
> </details>
> The syntax is correct, but I can switch it to:

`click: function() {
    ...
}`

---

_[src/js/components/OnlineInput.js, line 43 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0iZmRJvXo73UhECyE:-KM4brORoOHdlX_S-iiS:985214773) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/OnlineInput.js#L43)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Let's put this on one line
> </details>
> When it's on one line, it goes past the 80 character mark, but for now, I moved it to one line. 

---

_[src/js/components/UploadModal.js, line 60 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42#-KM0iqRkx23wHrn43xGD:-KM4bz1i5h0tCNg93ruq:-775595702) ([raw file](https://github.com/wycliffeassociates/8woc/blob/01839879fe45ec3f614dc7926cd8ea78e4f9deda/src/js/components/UploadModal.js#L60)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> One line.
> </details>
> See above comment

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42)_

**Comment by vleong2332** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/42)_

**Pull request merged**
