### PR TITLE
Sf dynamically load modules

### PR DESCRIPTION
**Pull request by ihoegen**
Created pull request for @therealsamf

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/112)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

_[index.html, line 19 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzJCx7wmivSxLyLgF4:-KMzJCx7wmivSxLyLgF5:1632604925) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/index.html#L19)):_

> ``` HTML
>     <script src="requirements.js"></script>
>     <script type="text/javascript">
>       console.log('Beginning Dynamic loading');
> ```

Is this supposed to be there?

---

_[modules/lexical_check_module/Door43DataFetcher.js, line 41 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzJJDMJ-a-bFhTALY_:-KMzJJDOCFcSAcM5P_Kq:481161300) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/modules/lexical_check_module/Door43DataFetcher.js#L41)):_

> ``` JavaScript
>        * the request
>        */
>       function getChaptersFromObject(obj) {
> ```

We should replace tabs with spaces. I'll take a look into this for sublime

---

_[modules/lexical_check_module/View.js, line 18 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzK_YPDMXf3U2tp-6t:-KMzK_YQIPGoibyR-3vu:677098019) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/modules/lexical_check_module/View.js#L18)):_

> ``` JavaScript
>       return (
>           <div>
>               <this.TPane />
> ```

Tabs

---

_[modules/t_pane/Book.js, line 93 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzLLEwDDhi5UBVgBr6:-KMzLLExyYWfGLwcHaeg:817686225) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/modules/t_pane/Book.js#L93)):_

> ``` JavaScript
>  //                        );
>  //                    }
>  //                }
> ```

Maybe remove this if it's not going to be used

---

_[modules/t_pane/BookTitle.js, line 23 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzLQJ6ngwqg4Aw3uCn:-KMzLQJ7oC2jt7UYd1ON:676771481) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/modules/t_pane/BookTitle.js#L23)):_

> ``` JavaScript
> // const BookTitle = React.createClass({
> //   render: function() {
> //     return (
> ```

Ibid

---

_[modules/t_pane/Chapter.js, line 33 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzLSJi0fN66szpKv3g:-KMzLSJi0fN66szpKv3h:676771481) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/modules/t_pane/Chapter.js#L33)):_

> ``` JavaScript
> //           <strong>Chapter {this.props.chapterNum}</strong>
> //         </h5>
> //         <div>{this.props.arrayOfVerses}</div>
> ```

Ibid

---

_[modules/t_pane/FetchData.js, line 191 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzLVTci-Nyd2A0ZwGa:-KMzLVTci-Nyd2A0ZwGb:677098019) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/modules/t_pane/FetchData.js#L191)):_

> ``` JavaScript
>   return length;
> }
> ```

Tabs

---

_[modules/t_pane/Pane.js, line 34 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzLXFkRnn2dFmvsjXL:-KMzLXFkRnn2dFmvsjXM:1730178010) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/modules/t_pane/Pane.js#L34)):_

> ``` JavaScript
> // const Pane = React.createClass({
> //     render: function() {
> //         return (
> ```

Possibly Remove

---

_[modules/t_pane/Verse.js, line 21 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzLc4I_r7BPMuMxO2R:-KMzLc4I_r7BPMuMxO2S:-1428671178) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/modules/t_pane/Verse.js#L21)):_

> ``` JavaScript
>               {this.props.verseText}
>           </p>
>       );
> ```

Replace tabs with spaces

---

_[src/js/components/core/NavigationMenu.js, line 2 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzLw8q15xU4Xdpe-YD:-KMzLw8rFvTGqKxEdOYU:287859177) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/src/js/components/core/NavigationMenu.js#L2)):_

> ``` JavaScript
> // const React = require('react');
> // const Well = require('react-bootstrap/lib/Well.js');
> ```

Possibly just delete

---

_[src/js/components/modules/lexical_check_module/CheckModuleView.js, line 17 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzM04tutSJrkrTvota:-KMzM04tutSJrkrTvotb:1666610317) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/src/js/components/modules/lexical_check_module/CheckModuleView.js#L17)):_

> ``` JavaScript
> const CheckStore = require('../../../stores/CheckStore.js');
> 
> console.log('We being require');
> ```

Remove log

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112)_

**Comment by lancelebanoff** [comment]
Review status: 46 of 58 files reviewed at latest revision, 11 unresolved discussions.

---

_[src/js/components/core/NavigationMenu.js, line 2 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzLw8q15xU4Xdpe-YD:-KMzXd8AG5kTKr05GGkx:961264418) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9d82bbf113289d35ae95ceab7ed0bf900911b5e4/src/js/components/core/NavigationMenu.js#L2)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> Possibly just delete
> </details>
> Noooo don't delete this. Just don't require it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112)_

**Comment by ihoegen** [comment]
@lancelebanoff I mean the stuff that was commented out lol

**Comment by ihoegen** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

_[modules/translation_academy/FetchData.js, line 11 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzaN3w1AxMkng0P41F:-KMzaN3x9C4FNkQ_BuwZ:677098019) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7e26b7e99f2beb3e7d70f2e9f63203eedd51cf9e/modules/translation_academy/FetchData.js#L11)):_

> ``` JavaScript
>           api.putDataInCheckStore("TranslationAcademy", "sectionList", data);
>           callback();
>       }
> ```

Tabs

---

_[modules/translation_academy/TranslationAcademyDisplay.js, line 68 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzapUvKQp_unxPOXgQ:-KMzapUvKQp_unxPOXgR:1417047473) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7e26b7e99f2beb3e7d70f2e9f63203eedd51cf9e/modules/translation_academy/TranslationAcademyDisplay.js#L68)):_

> ``` JavaScript
> 
>   getAndDisplaySection: function() {
>     var _this = this;
> ```

If this is all commented out, you could delete it

---

_[modules/translation_academy/View.js, line 33 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzaxphmkbgDtWCtm8U:-KMzaxpivCDruU8r3BnA:677098019) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7e26b7e99f2beb3e7d70f2e9f63203eedd51cf9e/modules/translation_academy/View.js#L33)):_

> ``` JavaScript
>   }
> 
>   render() {
> ```

Tabs

---

_[modules/translation_academy/react-remarkable/.jshintrc, line 8 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzb0TR7wIje-ooZBty:-KMzb0TR7wIje-ooZBtz:1774418055) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7e26b7e99f2beb3e7d70f2e9f63203eedd51cf9e/modules/translation_academy/react-remarkable/.jshintrc#L8)):_

> ``` JSON
>   "node": true,
>   "browser": true,
> ```

What is this for? 

---

_[modules/translation_academy/react-remarkable/package.json, line 11 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzb4qFeb7sBHp3SvnQ:-KMzb4qFeb7sBHp3SvnR:487733888) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7e26b7e99f2beb3e7d70f2e9f63203eedd51cf9e/modules/translation_academy/react-remarkable/package.json#L11)):_

> ``` JSON
>   "_id": "react-remarkable@1.1.1",
>   "_inCache": true,
>   "_installable": true,
> ```

This doesn't seem to be in the right location

---

_[modules/translation_academy/react-remarkable/README.md, line 9 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzb9PW1qE87B_OyJ63:-KMzb9PW1qE87B_OyJ64:676771481) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7e26b7e99f2beb3e7d70f2e9f63203eedd51cf9e/modules/translation_academy/react-remarkable/README.md#L9)):_

> ``` Markdown
> npm install --save react-remarkable
> ```
> 
> ```
> ```

Ibid

---

_[src/js/components/core/Toggle.js, line 3 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzbCWthnbVjXqdMMvq:-KMzbCWthnbVjXqdMMvr:865231561) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7e26b7e99f2beb3e7d70f2e9f63203eedd51cf9e/src/js/components/core/Toggle.js#L3)):_

> ``` JavaScript
> const React = require('react');
> const Button = require('react-bootstrap/lib/Button');
> // const CoreActions = require('../../actions/CoreActions.js');
> ```

Just delete it if you're not gonna use it

---

_[src/js/pages/app.js, line 4 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112#-KMzbGvdggpM4_RGKu8g:-KMzbGvdggpM4_RGKu8h:676771481) ([raw file](https://github.com/wycliffeassociates/8woc/blob/7e26b7e99f2beb3e7d70f2e9f63203eedd51cf9e/src/js/pages/app.js#L4)):_

> ``` JavaScript
>   const bootstrap = require('react-bootstrap');
> // const NavBarComponent = require('../components/core/NavBarComponent');
> ```

Ibid

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/112)_

**Pull request merged**
