### PR TITLE
Navigation menu

### PR DESCRIPTION
**Pull request by lancelebanoff**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/80)

### CODE REVIEW

**Comment by vleong2332** [comment]
Reviewed 12 of 12 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[.gitignore, line 232 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5xC2d6BkthzLx4kSH:-KM5xC2d6BkthzLx4kSI:588959223) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/.gitignore#L232)):_

> ```
> #Mr Developer
> .mr.developer.cfg
> gulpfile.js
> ```

Why is this being ignored?

---

_[src/js/components/MenuItem.js, line 25 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5xZcRxGUscVRNd_7R:-KM5xZcRxGUscVRNd_7S:2013195523) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/src/js/components/MenuItem.js#L25)):_

> ``` JavaScript
>     var flagStyle;
>     if (this.props.check.flagged) {
>       flagStyle = style.menu_item_flag_enabled;
> ```

:fearful: what are those underscores?

---

_[src/js/components/MenuItem.js, line 48 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5xk9d8YXc8si8eBmQ:-KM5xk9d8YXc8si8eBmR:-1446459354) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/src/js/components/MenuItem.js#L48)):_

> ``` JavaScript
>       default:
>         glyphIcon = '';
>         checkStatusStyle = style.menu_item_status_icon_unchecked;
> ```

More underscores :crying_cat_face: 

---

_[src/js/components/Style.js, line 54 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5yDQeangV8DKvibcQ:-KM5yDQeangV8DKvibcR:-238653910) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/src/js/components/Style.js#L54)):_

> ``` JavaScript
>   },
>   menu_item_status_icon_unchecked: {
>     display: 'none'
> ```

What's the reason for not nesting some of these? For example:

```
menuItem: {
   text: {},
   flag: {
      enabled: {},
      disabled: {},
   },
   ...
}
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80)_

**Comment by lancelebanoff** [comment]
Most of this stuff was me being stupid and doing quick fixes, hope these changes are sufficient

**Comment by lancelebanoff** [comment]
Review status: 9 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/js/components/MenuItem.js, line 25 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5xZcRxGUscVRNd_7R:-KM65Afn45URJ5KJi9au:2074425687) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/src/js/components/MenuItem.js#L25)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> :fearful: what are those underscores?
> </details>
> Replaced with camelCase

---

_[src/js/components/Style.js, line 54 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5yDQeangV8DKvibcQ:-KM65d0AjNOtuJwjYjS7:-276445994) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/src/js/components/Style.js#L54)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> What's the reason for not nesting some of these? For example:
> 
> ```
> menuItem: {
>    text: {},
>    flag: {
>       enabled: {},
>       disabled: {},
>    },
>    ...
> }
> ```
> 
> </details>
> Nested in most recent commit

---

_[.gitignore, line 232 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5xC2d6BkthzLx4kSH:-KM65hcwHt1U1lZKs8gx:1628222184) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/.gitignore#L232)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Why is this being ignored?
> </details>
> I was just being dumb

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80)_

**Comment by lancelebanoff** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[src/js/components/MenuItem.js, line 25 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5xZcRxGUscVRNd_7R:-KM9XBS2BQqlk16ACjBh:940986830) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/src/js/components/MenuItem.js#L25)):_
<details><summary>

<i>Previously, lancelebanoff wrote…</i></summary>



> Replaced with camelCase
> </details>
> Oops, haven't actually fixed this yet

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80)_

**Comment by lancelebanoff** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[src/js/components/MenuItem.js, line 25 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5xZcRxGUscVRNd_7R:-KM9aROIh4bzFC0jRgKO:1025776712) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/src/js/components/MenuItem.js#L25)):_
<details><summary>

<i>Previously, lancelebanoff wrote…</i></summary>



> Oops, haven't actually fixed this yet
> </details>
> Ok, now it's replaced with the nested styles

---

_[src/js/components/MenuItem.js, line 48 [r5]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-KM5xk9d8YXc8si8eBmQ:-KM9acF-NDfTckRj1w6F:-499146009) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5cd16c1237e979f26fda37883e98aaf1694b81fc/src/js/components/MenuItem.js#L48)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> More underscores :crying_cat_face: 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80)_

**Comment by vleong2332** [comment]
Reviewed 2 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80)_

**Comment by vleong2332** [comment]
@lancelebanoff, looks good. Just need to resolve the conflict and update the PR.

**Comment by lancelebanoff** [comment]
Done.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/80#-:-KM9k8gO80s3JUfY26zM:-499146009)_

**Pull request merged**
