### PR TITLE
Linted files and added load button

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/294)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 9 of 15 files at r1.
Review status: 9 of 15 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/294)_

**Comment by Gfuen** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/294)_

**Comment by RoyalSix** [comment]
Reviewed 5 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[src/js/components/core/LoadOnline.js, line 39 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/294#-KOAiAVnHYkS3PeGnqFx:-KOAiAVonDPoF-xKzRwj:-2018915841) ([raw file](https://github.com/wycliffeassociates/8woc/blob/1bd4f47b756fd9383f6ef9e114dd21ff2ce45320/src/js/components/core/LoadOnline.js#L39)):_

> ``` JavaScript
>           runGitCommand(savePath, url, callback);
>         });
>       } else {
> ```

simplicity! nice!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/294)_

**Comment by RoyalSix** [comment]
Reviewed 8 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/js/components/core/SideBar/SideNavBar.js, line 16 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/294#-KOAipo7B5ddHmvhnIeF:-KOAipo7B5ddHmvhnIeG:1545050787) ([raw file](https://github.com/wycliffeassociates/8woc/blob/1bd4f47b756fd9383f6ef9e114dd21ff2ce45320/src/js/components/core/SideBar/SideNavBar.js#L16)):_

> :+1: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/294)_

**Pull request merged**
