### PR TITLE
Workflow fixes

### PR DESCRIPTION
**Pull request by therealsamf**
This fixes a lot of workflow issues

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/297)

### CODE REVIEW

**Comment by therealsamf** [comment]
Also fixes in Lexical Checker

**Comment by RoyalSix** [comment]
Reviewed 5 of 42 files at r1.
Review status: 5 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

_[modules/lexical_check_module/GatewayVerseDisplay.js, line 23 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/297#-KOBIJyfgViGGHuNOY6L:-KOBIJyfgViGGHuNOY6M:736394103) ([raw file](https://github.com/wycliffeassociates/8woc/blob/81989fc165497522bf789e7f62b7e5f21d71d101/modules/lexical_check_module/GatewayVerseDisplay.js#L23)):_

> ``` JavaScript
>      * will never be found in the Bible
>      */
>     var first, last;
> ```

cool function!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/297)_

**Comment by EvanWiederspan** [comment]
Reviewed 37 of 42 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[modules/example_check_module/FetchData.js, line 79 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/297#-KOBHrOwVD5PpuDe3Qt2:-KOBHrOwVD5PpuDe3Qt3:1387235555) ([raw file](https://github.com/wycliffeassociates/8woc/blob/2ef9d4e973e2a75d2f0d55a90033ec632455af3f/modules/example_check_module/FetchData.js#L79)):_

> ``` JavaScript
>           console.log('Example Check Module');
>           callback();
>         }
> ```

do you still want these console logs?

---

_[modules/t_pane/FetchData.js, line 76 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/297#-KOBJWIXA0DumdnwY2Vm:-KOBJWIY_GfGdaF2B-kt:-814490658) ([raw file](https://github.com/wycliffeassociates/8woc/blob/2ef9d4e973e2a75d2f0d55a90033ec632455af3f/modules/t_pane/FetchData.js#L76)):_

> ``` JavaScript
>             // console.log('TPANE finished');
>             console.log('TPane callback');
>                   callback();
> ```

possibly unneccessary console logs and tabs here too  

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/297)_

**Comment by EvanWiederspan** [comment]
looks pretty good, only comments were concerning remaining console logs, so if you want to keep those for now go ahead and leave em in. Jay is gonna test your branch and then well pull

**Comment by ihoegen** [comment]
Reviewed 15 of 16 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/297)_

**Pull request merged**
