### PR TITLE
Login Component

### PR DESCRIPTION
**Pull request by ihoegen**
Add functionality for logging in and registering for accounts on the Door 43 website, using a GOGS API.

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/94)

### CODE REVIEW

**Comment by vleong2332** [comment]
Reviewed 8 of 17 files at r7, 20 of 21 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/Registration.js, line 31 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQab7b1duDg4EM40qi:-KMQab7b1duDg4EM40qj:-1159904590) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/components/core/Registration.js#L31)):_

> ``` JavaScript
>     } else if (password !== confirm && confirm.length > 0) {
>       return 'error';
>     }
> ```

What happens if the `confirm` is an empty string?

---

_[src/js/components/core/Registration.js, line 80 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQbPTgNvCH9FiAzd1_:-KMQbPTh6S31UsluJjVE:1118269629) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/components/core/Registration.js#L80)):_

> ``` JavaScript
>   validateEmail: function() {
>     var email = this.state.email;
>     if (email.length > 0) {
> ```

What happens if email is an empty string?

---

_[src/js/components/core/Registration.js, line 84 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQbWEliScRAL9UW1ep:-KMQbWEliScRAL9UW1eq:1054651714) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/components/core/Registration.js#L84)):_

> ``` JavaScript
>       if (reg.test(email)) {
>         return 'success';
>       } else {
> ```

What you did is perfectly valid and fine. But, if all it does is returning `success` or `error`, you can use ternary expression to write this.

```
return reg.test(email) ? 'success' : 'error';
```

---

_[src/js/components/core/Toggle.js, line 25 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQcZdwjeD9d3yNItxw:-KMQcZdwjeD9d3yNItxx:-477068136) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/components/core/Toggle.js#L25)):_

> ``` JavaScript
>   render(){
>     const text = this.state.online ? 'Online' : 'Offline';
>     const statusColor = this.state.buttonColor ? 'success' : 'danger';
> ```

There's the ternary :)

---

_[src/js/styles/loginStyle.js, line 18 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQcgGChJLOGGICZxxt:-KMQcgGChJLOGGICZxxu:-1531843752) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/styles/loginStyle.js#L18)):_

> ``` JavaScript
>     height: '60px',
>     width: '60px',
>     margin: '0px'
> ```

The convention is that if it's `0px`, it should be written as `0`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94)_

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/Registration.js, line 31 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQab7b1duDg4EM40qi:-KMQegu7Xbecl2DFc5E-:-762471412) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/components/core/Registration.js#L31)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> What happens if the `confirm` is an empty string?
> </details>
> The validator stays blank. This is mainly just a UI feature, letting the user know that there password does not match. I don't want to display the flag when they're empty.

---

_[src/js/components/core/Registration.js, line 80 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQbPTgNvCH9FiAzd1_:-KMQew4vyCcgMYGkMUgH:975241836) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/components/core/Registration.js#L80)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> What happens if email is an empty string?
> </details>
> Nothing happens, but if they are to submit, nothing happens. 

---

_[src/js/components/core/Registration.js, line 84 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQbWEliScRAL9UW1ep:-KMQf-vClvXr-RajCYg3:-568635119) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/components/core/Registration.js#L84)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> What you did is perfectly valid and fine. But, if all it does is returning `success` or `error`, you can use ternary expression to write this.
> 
> ```
> return reg.test(email) ? 'success' : 'error';
> ```
> 
> </details>
> Okay I will keep that in mind. 

---

_[src/js/components/core/Toggle.js, line 25 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQcZdwjeD9d3yNItxw:-KMQf2VAyCdV2AMZKT_7:-269476816) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/components/core/Toggle.js#L25)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> There's the ternary :)
> </details>
> Manny wrote this one :)

---

_[src/js/styles/loginStyle.js, line 18 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMQcgGChJLOGGICZxxt:-KMQf4z2JQFDx3aXof4d:1085485804) ([raw file](https://github.com/wycliffeassociates/8woc/blob/9b2680480ffba76c89ce3a2c9ad212f5f1ecdcfc/src/js/styles/loginStyle.js#L18)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> The convention is that if it's `0px`, it should be written as `0`
> </details>
> Will fix

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94)_

**Comment by vleong2332** [comment]
Reviewed 1 of 21 files at r8, 9 of 10 files at r9, 6 of 6 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/LoginModal.js, line 25 [r7]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMVRKUcIAFifppqds9p:-KMVRKUcIAFifppqds9q:542335717) ([raw file](https://github.com/wycliffeassociates/8woc/blob/244433383d72eb0cc652eee266f7a4cc3552b2ed/src/js/components/core/LoginModal.js#L25)):_

> ``` JavaScript
> 
>     componentWillUnmount() {
>       CoreStore.removeChangeListener(this.updateLoginModal.bind(this));
> ```

Why are these removed?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94)_

**Comment by ihoegen** [comment]
Review status: 12 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/js/components/core/LoginModal.js, line 21 [r7]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KM_gU4sfvCow41BRGt0:-KM_gU4tEUcFFcEIyOQt:-1495290133) ([raw file](https://github.com/wycliffeassociates/8woc/blob/244433383d72eb0cc652eee266f7a4cc3552b2ed/src/js/components/core/LoginModal.js#L21)):_

> ``` JavaScript
> 
>     componentWillUnmount() {
>       CoreStore.removeChangeListener(this.updateLoginModal.bind(this));
> ```

This is looking like a duplicate. 

---

_[src/js/components/core/LoginModal.js, line 25 [r7]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KMVRKUcIAFifppqds9p:-KM_gX5F54Bgx99r3WZI:1270629109) ([raw file](https://github.com/wycliffeassociates/8woc/blob/244433383d72eb0cc652eee266f7a4cc3552b2ed/src/js/components/core/LoginModal.js#L25)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Why are these removed?
> </details>
> It's removed in the case that the react component is terminated. From what I understand, it is just good practice. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94)_

**Comment by ihoegen** [comment]
Reviewed 5 of 5 files at r12, 10 of 10 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/LoginModal.js, line 21 [r7]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94#-KM_gU4sfvCow41BRGt0:-KM_hVnTrnm7d7AfbIYG:568033745) ([raw file](https://github.com/wycliffeassociates/8woc/blob/244433383d72eb0cc652eee266f7a4cc3552b2ed/src/js/components/core/LoginModal.js#L21)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> This is looking like a duplicate. 
> </details>
> Nevermind

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/94)_

**Comment by ihoegen** [comment]
@vleong2332 Looks good to me, merge when you feel all is well

**Pull request merged**
