### PR TITLE
Greek definitions integrated with popover. 

### PR DESCRIPTION
**Pull request by ihoegen**
This pull request will bring in a feature where if a user clicks on a greek word in the original language, a popover will appear with the definition inside. 

Also, enhancements were made to the opening of the app.

Issue #323 should also be solved.

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/325)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 27 of 30 files at r1, 1 of 4 files at r4, 5 of 7 files at r5, 1 of 4 files at r6, 5 of 9 files at r7, 2 of 2 files at r8, 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[modules/t_pane/FetchData.js, line 217 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXR5aE8tVWObFI21j:-KOfXR5bIieM4mjLXeyN:b-9dyfnv) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/modules/t_pane/FetchData.js#L217)):_

> ``` JavaScript
> function len(obj) {
>   var length = 0;
>   for (let item in obj) {
> ```

remove tabs

---

_[modules/t_pane/TPane.js, line 27 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXYbJLKkF8NLFlBqw:-KOfXYbJLKkF8NLFlBqx:bb7ozr7) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/modules/t_pane/TPane.js#L27)):_

> ``` JavaScript
>       var originalLanguage = api.getDataFromCommon('parsedGreek');
>       if (!originalLanguage) {
>       parseGreek();
> ```

tabs

---

_[modules/t_pane/TPane.js, line 125 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXZoSf7HiSifUHBCZ:-KOfXZoSf7HiSifUHBC_:b-7j1hd7) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/modules/t_pane/TPane.js#L125)):_

> ``` JavaScript
>       parsedText[ch] = {};
>       let chap = origText[ch];
>       for (let v in chap) {
> ```

tabsx

---

_[modules/t_pane/Verse.js, line 11 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXfvddY1zNrvG3Svz:-KOfXfvddY1zNrvG3Sw-:bb7ozr7) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5fb248fc85e78d719a3bbb08fbc568cb8ed03d1d/modules/t_pane/Verse.js#L11)):_

> ``` JavaScript
> 
> class Verse extends React.Component {
>   constructor() {
> ```

tabs

---

_[modules/t_pane/Verse.js, line 28 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXh16QJn0tncdZITI:-KOfXh16QJn0tncdZITJ:bb7ozr7) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5fb248fc85e78d719a3bbb08fbc568cb8ed03d1d/modules/t_pane/Verse.js#L28)):_

> ``` JavaScript
>           <p>
>         <strong className={this.state.highlighted ? 'text-primary' : ''}>{this.props.verseNumber} </strong>
>               <span className={this.state.highlighted ? 'text-primary' : ''}>{this.props.verseText}</span>
> ```

tabs

---

_[modules/t_pane/Verse.js, line 29 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXidSc1JQxvbfVvUl:-KOfXidSc1JQxvbfVvUm:bb7ozr7) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5fb248fc85e78d719a3bbb08fbc568cb8ed03d1d/modules/t_pane/Verse.js#L29)):_

> ``` JavaScript
>         <strong className={this.state.highlighted ? 'text-primary' : ''}>{this.props.verseNumber} </strong>
>               <span className={this.state.highlighted ? 'text-primary' : ''}>{this.props.verseText}</span>
>           </p>
> ```

tabs

---

_[modules/t_pane/Verse.js, line 47 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXi4p3dgGQvecmGxd:-KOfXi4p3dgGQvecmGxe:bb7ozr7) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/modules/t_pane/Verse.js#L47)):_

> ``` JavaScript
>                             key={i++}
>                             strong={word.strong}
>                           style={{cursor: 'pointer'}}
> ```

tabs

---

_[src/js/ModuleApi.js, line 30 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXkt6zThcLwJUM7eo:-KOfXkt7quWeRDtiP5r1:bfcwf15) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/src/js/ModuleApi.js#L30)):_

> ``` JavaScript
>     this.Popover = require('./components/core/PopoverApi');
>     this.Toast = require('./NotificationApi/ToastApi');
>   this.Git = require('./components/core/GitApi.js');
> ```

tabs, praying for you brother

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325)_

**Comment by mannycolon** [comment]
Reviewed 1 of 4 files at r10.
Review status: 41 of 44 files reviewed at latest revision, 10 unresolved discussions.

---

_[modules/t_pane/FetchData.js, line 218 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfcKTHeGdllyutPKqq:-KOfcKTHeGdllyutPKqr:blo31mr) ([raw file](https://github.com/wycliffeassociates/8woc/blob/e05b5026063c87191bbc8b7f4940819746f14f85/modules/t_pane/FetchData.js#L218)):_

> ``` JavaScript
>       var length = 0;
>       for (let item in obj) {
>           length++;
> ```

tabs again

---

_[modules/t_pane/TPane.js, line 118 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfcS0-niTbLKvH75I0:-KOfcS0-niTbLKvH75I1:b-kaxsl9) ([raw file](https://github.com/wycliffeassociates/8woc/blob/00ebe03ebb409f9a9f5a96d4c6a3dbb113c55677/modules/t_pane/TPane.js#L118)):_

> ``` JavaScript
>   var lex = require("./Lexicon.json");
>   let origText = api.getDataFromCommon("originalLanguage");
>   let parsedText = {};
> ```

tabsnn

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325)_

**Comment by mannycolon** [comment]
you still have tabs

**Comment by ihoegen** [comment]
You've got to be kidding me.

**Comment by EvanWiederspan** [comment]
I just pulled this branch and its still not working, the loading screen stays open when i switch from lexical to example check

**Comment by ihoegen** [comment]
Did it open existing projects okay?

**Comment by ihoegen** [comment]
It may have something to do with changes made after the merge with sams. I have a local branch, now remote that merged sam's fixes. ih-greek would have this merged branch, which works.

**Comment by EvanWiederspan** [comment]
it opened projects with lexical fine, yeah, but example check module seems messed up somehow. Its happening on develop too though so its probably unrelated to this particular pull request

**Comment by EvanWiederspan** [comment]
also, this branch currently doesn't save anything to the TPane namepsace (no TPane.tc is being made in checkData) so we dont really know at this point if this stuff fixed the problem. Im gonna play around and try to move the parsed greek back into the TPane namespace and see if that works now

**Comment by ihoegen** [comment]
Opening existing works. Along with switching from lexical to phrase and back to lexical. It appears to be an issue with solely example check module. I'll look into it as well.

**Comment by ihoegen** [comment]
I found it. Line 42 of the Example Check Module view, the method to grab the tpane from the api is commented out. TPane is still used later. I'm going to uncomment it and see if it works.

**Comment by EvanWiederspan** [comment]
yeah i think the example check problems are in the module itself, the errors im getting are related to the View returning null stuff, so i think we can leave that for a different pull request

**Comment by ihoegen** [comment]
I fixed it. I just had to uncomment where tpane is set to the api.getModule() function and it works. I'll push that right now.

**Comment by mannycolon** [comment]
Reviewed 2 of 4 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325)_

**Comment by mannycolon** [comment]
Please make sure it works and then we can just merge

**Comment by ihoegen** [comment]
It should be on the remote now.

**Comment by EvanWiederspan** [comment]
kk, i think we still need a few more things before we pull it in. First, it doesnt actually store anything in the TPane namespace right now, i moved it to common so that it would work but i think we should move it back. Also, the parsing is done in the TPane constructor right now, and really should probably be moved to its' FetchData instead

**Comment by EvanWiederspan** [comment]
i can work on that right now, ill let you guys know how it works out

**Comment by ihoegen** [comment]
Sounds good to me.

**Comment by EvanWiederspan** [comment]
aight it looks like its working now, TPane puts the parsed greek in its own namespace and does the parsing in FetchData instead of in the TPane constructor. I think were good to merge in if someone wants to review and test my stuff real fast

**Comment by ihoegen** [comment]
I can do a review on it, but can't test it at the moment. If someone could test it then merge when it works, that'd be great.

**Comment by ihoegen** [comment]
Review status: 42 of 45 files reviewed at latest revision, 10 unresolved discussions.

---

_[modules/t_pane/FetchData.js, line 217 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXR5aE8tVWObFI21j:-KOhO7d4OFmrpw201PcG:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/modules/t_pane/FetchData.js#L217)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> remove tabs
> </details>
> Done.

---

_[modules/t_pane/FetchData.js, line 218 [r10]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfcKTHeGdllyutPKqq:-KOhO6Ysxv_Kz8jr5YjC:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/e05b5026063c87191bbc8b7f4940819746f14f85/modules/t_pane/FetchData.js#L218)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs again
> </details>
> Done.

---

_[modules/t_pane/TPane.js, line 118 [r8]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfcS0-niTbLKvH75I0:-KOhOAeAE7hC-aM-CbQU:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/00ebe03ebb409f9a9f5a96d4c6a3dbb113c55677/modules/t_pane/TPane.js#L118)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabsnn
> </details>
> Done.

---

_[modules/t_pane/TPane.js, line 27 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXYbJLKkF8NLFlBqw:-KOhO8yC-7ByjQnS4HDQ:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/modules/t_pane/TPane.js#L27)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs
> </details>
> Done.

---

_[modules/t_pane/TPane.js, line 125 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXZoSf7HiSifUHBCZ:-KOhOBt94G8EE8y5Ek5I:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/modules/t_pane/TPane.js#L125)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabsx
> </details>
> Done.

---

_[modules/t_pane/Verse.js, line 11 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXfvddY1zNrvG3Svz:-KOhODZ33TExCrTrrsMi:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5fb248fc85e78d719a3bbb08fbc568cb8ed03d1d/modules/t_pane/Verse.js#L11)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs
> </details>
> Done.

---

_[modules/t_pane/Verse.js, line 28 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXh16QJn0tncdZITI:-KOhOEZxU5QyVuLlj937:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5fb248fc85e78d719a3bbb08fbc568cb8ed03d1d/modules/t_pane/Verse.js#L28)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs
> </details>
> Done.

---

_[modules/t_pane/Verse.js, line 29 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXidSc1JQxvbfVvUl:-KOhOHKFHm3cxqEFMAFB:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5fb248fc85e78d719a3bbb08fbc568cb8ed03d1d/modules/t_pane/Verse.js#L29)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs
> </details>
> Done.

---

_[modules/t_pane/Verse.js, line 47 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXi4p3dgGQvecmGxd:-KOhOGGqfjMv5YhZqTfY:b-896fix) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/modules/t_pane/Verse.js#L47)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs
> </details>
> Done.

---

_[src/js/ModuleApi.js, line 30 [r9]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325#-KOfXkt6zThcLwJUM7eo:-KOhOIopkr4f0BQgYAnT:b-pkrlev) ([raw file](https://github.com/wycliffeassociates/8woc/blob/707667f4c399e0d8126d18557c3951209da79233/src/js/ModuleApi.js#L30)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs, praying for you brother
> </details>
> Prayed for. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325)_

**Comment by ihoegen** [comment]
Nevermind, it won't let me review it for some reason. It's up to @mannycolon

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r12, 2 of 2 files at r13.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/325)_

**Comment by ihoegen** [comment]
@mannycolon If you think it's good, merge it in.

**Pull request merged**
