### PR TITLE
Propose Changes Module Initial integration

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/128)

### CODE REVIEW

**Comment by mannycolon** [comment]
#49 #44 #115

**Comment by ihoegen** [comment]
The button is a little buggy. Come to me and I'll show it

**Comment by ihoegen** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

_[modules/proposed_changes_module/FetchDataGuide.js, line 23 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/128#-KN3skaL8uX55xGnLQPx:-KN3skaL8uX55xGnLQPy:540879387) ([raw file](https://github.com/wycliffeassociates/8woc/blob/015ce5ab9f3dbf5bfc1416d3f739af6b27fd6596/modules/proposed_changes_module/FetchDataGuide.js#L23)):_

> ``` JavaScript
>           dispatcher.schedule(function(subCallback) {sendToReader(params.targetLanguagePath, subCallback)});
>       }
>   }
> ```

Replace these tabs with spaces.

---

_[modules/translation_academy/react-remarkable/node_modules/.bin/remarkable, line 0 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/128#-KN3swubMhmdrUFL6LaJ:-KN3swubMhmdrUFL6LaK:2086131766) ([raw file](https://github.com/wycliffeassociates/8woc/blob/015ce5ab9f3dbf5bfc1416d3f739af6b27fd6596/modules/translation_academy/react-remarkable/node_modules/.bin/remarkable#L0)):_
We gotta figure out this remarkable stuff

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/128)_

**Comment by ihoegen** [comment]
Reviewed 4 of 6 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/js/stores/CheckStore.js, line 201 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/128#-KN3x6A1KCFtctcMJm4o:-KN3x6A2zYf_hpcabwml:-1588092002) ([raw file](https://github.com/wycliffeassociates/8woc/blob/967ea11853640981de0d74b9828286bd2be3ed99/src/js/stores/CheckStore.js#L201)):_

> ``` JavaScript
>       for (var actionCallback of this.actionCallbacks[action.type]) {
>         console.log('StoreData');
>         console.dir(this.storeData);
> ```

Remove these console logs. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/128)_

**Comment by ihoegen** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/128)_

**Pull request merged**
