### PR TITLE
Abstract Check Module and Flux parts for Checks

### PR DESCRIPTION
**Pull request by loganlebanoff**
- Abstract class for Check Modules. Check Modules -- like LexicalCheckModule -- should extend AbstractCheckModule.
- CheckStore and CheckActions
- Example Check Module that extends the abstract class and uses the new Flux stores and actions
- Utils file for common functions

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/31)

### CODE REVIEW

**Comment by vleong2332** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/utils.js, line 12 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/31#-KM-TpCiH1hexZU25Mun:-KM-TpCiH1hexZU25Muo:-651870641) ([raw file](https://github.com/wycliffeassociates/8woc/blob/44fa9bf5e6599d855e990a6d2c33a7965c32073c/src/js/utils.js#L12)):_

> ``` JavaScript
>             return obj;
>         }
>         var temp = obj.constructor(); // give temp the original obj's constructor
> ```

Comment should go above the code that it comments on.

---

_[src/js/components/AbstractCheckModule.js, line 18 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/31#-KM-UOGJ8dlbcKLN_ims:-KM-UOGJ8dlbcKLN_imt:788882678) ([raw file](https://github.com/wycliffeassociates/8woc/blob/44fa9bf5e6599d855e990a6d2c33a7965c32073c/src/js/components/AbstractCheckModule.js#L18)):_

> ``` JavaScript
>     super();
> 
>     this.state = {currentCheck : CheckStore.getCurrentCheck()};
> ```

Colon needs to stick to the left operand.

---

_[src/js/components/AbstractCheckModule.js, line 35 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/31#-KM-UayUopkOlqd6jUWz:-KM-UayUopkOlqd6jUX-:-1732803383) ([raw file](https://github.com/wycliffeassociates/8woc/blob/44fa9bf5e6599d855e990a6d2c33a7965c32073c/src/js/components/AbstractCheckModule.js#L35)):_

> ``` JavaScript
>     this.setState({currentCheck: CheckStore.getCurrentCheck()});
>   }
> 
> ```

Empty spaces.

---

_[src/js/components/ExampleCheckModule.js, line 31 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/31#-KM-UwjE6HXi_d4ORMVr:-KM-UwjE6HXi_d4ORMVs:-1732803383) ([raw file](https://github.com/wycliffeassociates/8woc/blob/44fa9bf5e6599d855e990a6d2c33a7965c32073c/src/js/components/ExampleCheckModule.js#L31)):_

> ``` JavaScript
>     CheckActions.changeCheckProperty("checkStatus", "RETAINED");
>   }
> 
> ```

Empty spaces.

---

_[src/js/stores/CheckStore.js, line 12 [r2]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/31#-KM-V6mrQoMHO5cXEWY1:-KM-V6mrQoMHO5cXEWY2:-1542186657) ([raw file](https://github.com/wycliffeassociates/8woc/blob/44fa9bf5e6599d855e990a6d2c33a7965c32073c/src/js/stores/CheckStore.js#L12)):_

> ``` JavaScript
>     super();
>     // For ExampleCheckModule
>     this.currentCheck = { checkStatus: "UNCHECKED", comments: "" };
> ```

One-line object literal shouldn't have spaces in the beginning and the end of its properties.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/31)_

**Comment by vleong2332** [comment]
Great job. Most of the comments are just about formatting.

**Comment by loganlebanoff** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/31)_

**Comment by vleong2332** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/31)_

**Pull request merged**
