### PR TITLE
Added Core Store

### PR DESCRIPTION
**Pull request by loganlebanoff**
The Flux pattern is ready to use

Added Core Store

Added ExampleComponent to illustrate using Flux

Adjusted existing CoreActions and Dispatcher to match CoreStore

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/25)

### CODE REVIEW

**Comment by vleong2332** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[src/js/CoreActions.js, line 34 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLW_EzokWjPzkP-4iWX:-KLW_EzokWjPzkP-4iWY:1668250406) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/CoreActions.js#L34)):_

> ``` JavaScript
> 
> };
> window.addToText = module.exports.addToText;
> ```

I'm not sure what this does, but any global variable (stored in `window`) makes me think twice. Can you explain it to me?

---

_[src/js/CoreStore.js, line 29 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLW_ZIEUUac70sN62iE:-KLW_ZIFfwGsGXEd9gby:-385878436) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/CoreStore.js#L29)):_

> ``` JavaScript
> (See ExampleComponent.js)
> 
> */
> ```

Great job on the documentation!

---

_[src/js/CoreStore.js, line 50 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLW_ol82SpNLqU0qZPa:-KLW_ol82SpNLqU0qZPb:736671702) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/CoreStore.js#L50)):_

> ``` JavaScript
>         // Emits that a change was made, so any
>         // component listening for this store
>         // can update its data
> ```

FYI: It's okay to let the line goes a bit longer.

---

_[src/js/CoreStore.js, line 67 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLW_urA8YfeL-uw4SsA:-KLW_urBwg7WsLiHCKqe:-34886083) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/CoreStore.js#L67)):_

> ``` JavaScript
>       case "ADD_TO_TEXT": {
>         this.exampleComponentText += "a";
>         this.emit("change");
> ```

Looks like `this.emit('change')` is being called regardless of the case. Maybe it can go outside the switch statement?

---

_[src/js/CoreStore.js, line 77 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLWa81P6UIa5s-5X4Tp:-KLWa81P6UIa5s-5X4Tq:-1765313608) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/CoreStore.js#L77)):_

> ``` JavaScript
> const coreStore = new CoreStore;
> Dispatcher.register(coreStore.handleActions.bind(coreStore));
> window.CoreStore = coreStore;
> ```

Same thing about the `window` comment

---

_[src/js/Dispatcher.js, line 10 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLWaDgdVuTH4axjEPBN:-KLWaDgdVuTH4axjEPBO:-1765313608) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/Dispatcher.js#L10)):_

> ``` JavaScript
>   );
> };
> window.Dispatcher = Dispatcher;
> ```

Same thing about the `window` comment

---

_[src/js/ExampleComponent.js, line 22 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLWaPfpAGFCPQJjHl3n:-KLWaPfpAGFCPQJjHl3o:1458472976) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/ExampleComponent.js#L22)):_

> ``` JavaScript
> 
>   getText() {
>     console.log(this);
> ```

FYI: If done debugging, we should remove this code.

---

_[src/js/index.js, line 11 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLWa_ZxsUDFFAoUgnjt:-KLWa_ZxsUDFFAoUgnju:-79803226) ([raw file](https://github.com/wycliffeassociates/8woc/blob/800bf3cdc31a5177a04f72fe581d5d4b2f2e794d/src/js/index.js#L11)):_

> ``` JavaScript
>   const CommentBox = require('./CommentBox');
>   const NextButton = require('./NextButton');
>   const CheckingScreen =  require('./CheckingScreen');
> ```

Why are these being removed?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25)_

**Comment by loganlebanoff** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[src/js/CoreActions.js, line 34 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLW_EzokWjPzkP-4iWX:-KLWchxOXvA08E_kYPI9:-1850371741) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/CoreActions.js#L34)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> I'm not sure what this does, but any global variable (stored in `window`) makes me think twice. Can you explain it to me?
> </details>
> Oh, that was for testing. I removed it and will commit.

---

_[src/js/CoreStore.js, line 67 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLW_urA8YfeL-uw4SsA:-KLWjkIRw8VdVYQL7JIt:-1924483522) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/CoreStore.js#L67)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Looks like `this.emit('change')` is being called regardless of the case. Maybe it can go outside the switch statement?
> </details>
> It will always do that, except for the default case. I added the default case to make that more clear and will commit.

---

_[src/js/CoreStore.js, line 77 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLWa81P6UIa5s-5X4Tp:-KLWjzyGQ8zXWv4e_jHW:-306065882) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/CoreStore.js#L77)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Same thing about the `window` comment
> </details>
> Also removed and will commit.

---

_[src/js/Dispatcher.js, line 10 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLWaDgdVuTH4axjEPBN:-KLWk3jLyWxumfJPWuJj:346116021) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/Dispatcher.js#L10)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Same thing about the `window` comment
> </details>
> Same thing.

---

_[src/js/ExampleComponent.js, line 22 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLWaPfpAGFCPQJjHl3n:-KLWkBQPJSsC984xcaiv:1740281843) ([raw file](https://github.com/wycliffeassociates/8woc/blob/f86b2c9cfb2f551465ecb54d0d1295e6e6e5484a/src/js/ExampleComponent.js#L22)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> FYI: If done debugging, we should remove this code.
> </details>
> Removed.

---

_[src/js/index.js, line 11 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25#-KLWa_ZxsUDFFAoUgnjt:-KLWkI8TwRiKeFZIW8Ga:-1815484802) ([raw file](https://github.com/wycliffeassociates/8woc/blob/800bf3cdc31a5177a04f72fe581d5d4b2f2e794d/src/js/index.js#L11)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Why are these being removed?
> </details>
> They aren't actually being displayed yet, so there is no point in the require statements being there.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25)_

**Comment by vleong2332** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25)_

**Comment by vleong2332** [comment]
@loganlebanoff, everything looks good. Just merge with the latest `develop` and resolve the conflict before pushing your branch again. If you're unsure, feel free to ask.

**Comment by vleong2332** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/25)_

**Pull request merged**
