### PR TITLE
New workflow implementation

### PR DESCRIPTION
**Pull request by EllDoubleYew**
This is the marriage of several different workflow-related branches. Primarily introducing the replacement of checks with apps in the way that they are loaded. There is still "polishing" to be done but this introduces all of the key functionality of the new workflow.

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/280)

### CODE REVIEW

**Comment by EvanWiederspan** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/js/components/core/SwitchCheckModal.js, line 61 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5DFJQu8CySTprF_Hf:-KO5DFJQu8CySTprF_Hg:547182330) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/SwitchCheckModal.js#L61)):_

> ``` JavaScript
>   render() {
>     if(!this.state.moduleMetadatas) {
>       console.error('No tC default modules found.');
> ```

return an empty div here

---

_[src/js/components/core/create_project/CheckDataGrabber.js, line 61 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5DLy23R4S53MY5MWq:-KO5DLy23R4S53MY5MWr:-1382714788) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/create_project/CheckDataGrabber.js#L61)):_

> ``` JavaScript
>   loadModuleAndDependencies: function(moduleFolderName) {
>     FileModule.readJsonFile(path.join(window.__base, "modules", moduleFolderName, "manifest.json"), (moduleMetadata) => {
>       var params = api.getDataFromCommon('params');
> ```

does there need to be error checking if this is undefined?

---

_[src/js/components/core/welcome/WelcomeUpload.js, line 60 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5DsHnwratBkca44qb:-KO5DsHnwratBkca44qc:1386068025) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/welcome/WelcomeUpload.js#L60)):_

> ``` JavaScript
> 
>   sendFilePath: function(path, link) {
>     var _this = this;
> ```

i dont think you need this in this function

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280)_

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/welcome/welcome.js, line 147 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5L5i-pTsLHg4XMOhu:-KO5L5i-pTsLHg4XMOhv:1906878405) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/welcome/welcome.js#L147)):_

> ``` JavaScript
>             <div style={Styles.tutorialPopover}>
>               <p>Clicking here will allow you to log out or see more information about your account</p>
>             </div>
> ```

Could we turn these into a single component and just use props to populate.

---

_[src/js/components/core/welcome/WelcomeUpload.js, line 32 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5LpwzL6LW7a6Q8aEq:-KO5Lpx-AmAvuaQxrvnn:724189966) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/welcome/WelcomeUpload.js#L32)):_

> ``` JavaScript
>        showFile: true,
>        params: {
>          originalLanguagePath: window.__base + "data/ulgb"
> ```

Verify that this not conflict with another window.__base

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280)_

**Comment by EllDoubleYew** [comment]
Reviewed 4 of 19 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/welcome/welcome.js, line 147 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5L5i-pTsLHg4XMOhu:-KO5NHa9D-aKjPqkuFWQ:-614563625) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/welcome/welcome.js#L147)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> Could we turn these into a single component and just use props to populate.
> </details>
> This would help the readability but this was done so that we could get the workflow finished on time. This is a refactor for a later version.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280)_

**Comment by loganlebanoff** [comment]
Review status: 18 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/SwitchCheckModal.js, line 61 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5DFJQu8CySTprF_Hf:-KO5Pl40WZmjKtObVNoO:-1163372636) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/SwitchCheckModal.js#L61)):_
<details><summary>

<i>Previously, EvanWiederspan (Evan Wiederspan) wrote…</i></summary>



> return an empty div here
> </details>
> Still returns the modal now, but the modal says that no default modules were found.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280)_

**Comment by RoyalSix** [comment]
Review status: 18 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/welcome/WelcomeUpload.js, line 32 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5LpwzL6LW7a6Q8aEq:-KO5OibN1dpOxjaxkxkS:1625866131) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/welcome/WelcomeUpload.js#L32)):_

> Verify that this not conflict with another window.__base
> this instance will not conflict :100: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280)_

**Comment by RoyalSix** [comment]
Review status: 18 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/welcome/WelcomeUpload.js, line 60 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5DsHnwratBkca44qb:-KO5SwXJqG--IjmgIwCu:676707911) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/welcome/WelcomeUpload.js#L60)):_
<details><summary>

<i>Previously, EvanWiederspan (Evan Wiederspan) wrote…</i></summary>



> i dont think you need this in this function
> </details>
> I do

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280)_

**Comment by loganlebanoff** [comment]
Review status: 18 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/create_project/CheckDataGrabber.js, line 61 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280#-KO5DLy23R4S53MY5MWq:-KO5TbaGMePo-JlyZ6VX:719748504) ([raw file](https://github.com/wycliffeassociates/8woc/blob/59d2e414d5c05d458c2b06a7a336029d7351461f/src/js/components/core/create_project/CheckDataGrabber.js#L61)):_
<details><summary>

<i>Previously, EvanWiederspan (Evan Wiederspan) wrote…</i></summary>



> does there need to be error checking if this is undefined?
> </details>
> I don't think we can do error checking for that right here. We can use the alert modal, but that will take a while and I think we should just push this through for now.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/280)_

**Pull request merged**
