### PR TITLE
Added a dropdown to choose a check module to work on.

### PR DESCRIPTION
**Pull request by loganlebanoff**
- SwitchCheckModuleDropdown has two dummy check modules to choose from (TODO: needs to read from a project manifest.json file in the future).
- This component sends an action which reads from the selected module's check_data.json. It puts this data into CheckStore to be ready for use by the check module.
- Added dummy check_data.json files to get the check data from.

---

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/8woc/91)

### CODE REVIEW

**Comment by vleong2332** [comment]
Reviewed 20 of 21 files at r1.
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[src/js/components/core/SwitchCheckModuleDropdown.js, line 42 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91#-KMQOJIhlJtojFOJpJH9:-KMQOJIi-8Tz1NEgii78:-50129864) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5606b89cdf5a1a85a6c49d8fcf834e3c4b6ff07c/src/js/components/core/SwitchCheckModuleDropdown.js#L42)):_

> ``` JavaScript
> 
>   getSelectedCheckCategoryId() {
>     return (this.state.checkCategory == undefined ? NONE_SELECTED : this.state.checkCategory.id);
> ```

Love the ternary expression.

What are the possible values for `checkCategory`? if falsy values are not the options for `checkCategory`, you can even write it as...

```
return this.state.checkCategory ? NONE_SELECTED : this.state.checkCategory.id;
```

---

_[src/js/components/core/SwitchCheckModuleDropdown.js, line 56 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91#-KMQOuQBvQcepZQSQ5f-:-KMQOuQBvQcepZQSQ5f0:1886457506) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5606b89cdf5a1a85a6c49d8fcf834e3c4b6ff07c/src/js/components/core/SwitchCheckModuleDropdown.js#L56)):_

> ``` JavaScript
>     var optionNodes = this.state.checkCategoryOptions.map(function(checkCategory){
>       return (
>         <option key={Math.random()} value={checkCategory.id}>{checkCategory.name}</option>
> ```

is `Math.random()` a valid practice for assigning `key`s?

---

_[src/js/stores/CheckStore.js, line 77 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91#-KMQPxRZVzzBSTa9fqea:-KMQPxRZVzzBSTa9fqeb:-10413405) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5606b89cdf5a1a85a6c49d8fcf834e3c4b6ff07c/src/js/stores/CheckStore.js#L77)):_

> ``` JavaScript
>     // Element not found
>     return undefined;
>   }
> ```

Suggestion:

```
findById(source, id) {
   return source.find(function(item) {
      return item.id === id;
   });
})
```

Double check that it works the same way. It should, but I could be wrong.

---

_[src/js/stores/CheckStore.js, line 92 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91#-KMQQhUwMuk0Eo6uM7E6:-KMQQhUx-3FOQFDPQBHu:523581702) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5606b89cdf5a1a85a6c49d8fcf834e3c4b6ff07c/src/js/stores/CheckStore.js#L92)):_

> ``` JavaScript
>     var checks;
>     for(var el in jsonObject) {
>       this.checks = jsonObject[el];
> ```

What's the difference between `checks` in 2 lines above and `this.checks`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91)_

**Comment by loganlebanoff** [comment]
Review status: 11 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/js/components/core/SwitchCheckModuleDropdown.js, line 42 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91#-KMQOJIhlJtojFOJpJH9:-KMS5JOSEp9bZzX84h-W:-2145536897) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5606b89cdf5a1a85a6c49d8fcf834e3c4b6ff07c/src/js/components/core/SwitchCheckModuleDropdown.js#L42)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Love the ternary expression.
> 
> What are the possible values for `checkCategory`? if falsy values are not the options for `checkCategory`, you can even write it as...
> 
> ```
> return this.state.checkCategory ? NONE_SELECTED : this.state.checkCategory.id;
> ```
> 
> </details>
> Thanks, you're right, it works in my case.

---

_[src/js/components/core/SwitchCheckModuleDropdown.js, line 56 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91#-KMQOuQBvQcepZQSQ5f-:-KMS5NCYdP8LjquWd8eC:-1567682341) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5606b89cdf5a1a85a6c49d8fcf834e3c4b6ff07c/src/js/components/core/SwitchCheckModuleDropdown.js#L56)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> is `Math.random()` a valid practice for assigning `key`s?
> </details>
> Oops, forgot about that. I changed it to its id.

---

_[src/js/stores/CheckStore.js, line 77 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91#-KMQPxRZVzzBSTa9fqea:-KMS8uAjorfyyfsVvCzb:-1821607441) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5606b89cdf5a1a85a6c49d8fcf834e3c4b6ff07c/src/js/stores/CheckStore.js#L77)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> Suggestion:
> 
> ```
> findById(source, id) {
>    return source.find(function(item) {
>       return item.id === id;
>    });
> })
> ```
> 
> Double check that it works the same way. It should, but I could be wrong.
> </details>
> It works!

---

_[src/js/stores/CheckStore.js, line 92 [r1]](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91#-KMQQhUwMuk0Eo6uM7E6:-KMS9_bGwIKFUZ5QKqV8:-1924755621) ([raw file](https://github.com/wycliffeassociates/8woc/blob/5606b89cdf5a1a85a6c49d8fcf834e3c4b6ff07c/src/js/stores/CheckStore.js#L92)):_
<details><summary>

<i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>



> What's the difference between `checks` in 2 lines above and `this.checks`?
> </details>
> Oops, that first "checks" doesn't do anything. Removed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91)_

**Comment by EvanWiederspan** [comment]
resolves issue #51

**Comment by vleong2332** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/wycliffeassociates/8woc/91)_

**Pull request merged**
